### ISSUE TITLE
Filtering - Tracking Issue

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#1632]
The following issues represent the outstanding work to complete Filtering examples:

- [ ] Implement filtering table example https://github.com/grommet/hpe-design-system/issues/1282 & https://github.com/grommet/hpe-design-system/issues/1343
- [ ] Apply FilterControls to remaining examples https://github.com/grommet/hpe-design-system/issues/1631
- [ ] Support FilterControls with test suite https://github.com/grommet/hpe-design-system/issues/1630

**Comment by halocline** [comment]
Closing in favor of following individual issues.
