### ISSUE TITLE
Site Search - Create branch demonstrating "immediate wins"

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#1828]
Parent issue: https://github.com/grommet/hpe-design-system/issues/1787

- [x] Create a "Search" branch on hpe-design-system
- [x] Provide a proof of concept to demonstrate the following:
  - [x] Remove query constraint (i.e. allow user to type anything they want and hit Enter)
  - [x] Search Results page/view/component
    - Component will accept an array of search results objects
    - Search results object should resemble:
```
{
  query: string,
  matchedText: string,
  matchType: string,
  url: string,
  preview: string | JSX.element,
}
```
  - [x] Add and populate the following items to a 4-5 `structure.js` page entries:
    - [x] Title synonyms
    - [x] Tags
  - [x] Expand metadata search matches including:
    - [x] Title (currently implemented)
    - [x] Section titles (currently implemented)
    - [x] Title synonyms
    - [x] Description
    - [x] Tags
- [x] Share link to demo branch ([Demo branch](https://deploy-preview-1842--keen-mayer-a86c8b.netlify.app/))
- [x] Create issue to incorporate UX feedback https://github.com/grommet/hpe-design-system/issues/1848
- [x] Create issue to populate expanded meta data (e.g. tags for each page, add page sections where appropriate) https://github.com/grommet/hpe-design-system/issues/1849
- [x] Create issue to demonstrate prototype for "content/document" search (i.e. searching a page's actual content) https://github.com/grommet/hpe-design-system/issues/1850
