### ISSUE TITLE
NameValueList remaining cleanups

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#2024]
**Brittany:**

**First Example**
- [x] Created On should be a date-time string
- [x] Format IP Address correctly

**Anatomy**
- [x] Align diagram connectors (Grid or Column boxes)
- [x] 3. Bold names for second icon visual
- [x] Make sure icons aria-hidden

**Figures**
- [x] Content overflows examples container (check mobile sizing)
- [x] Write captions to read as complete sentences with periods

**Horizontal**
- [x] Format date-time
- [x] Format IP Address
- [x] Update description "Full-service A.I. insights, security and unified infrastructure management for campus, branch, remote, and data center networks."

**Multiple**
- [x] NameValuelists --> NameValueLists
- [x] Remove showResponsiveControls

**Vertical Example**
- [x] Created On should be a date-time string
- [x] Format IP Address correctly

**Taylor:**

**Grid**
- [x] adjust for bottom pad
- [x] Remove showResponsiveControls

**Headings**
- [x] Add caption to Headings example
- [x] bottom padding

**Scale**
- [x] checks ot use text-strong
- [x] capitalize "name" in example
- [x] remove height on Don't for small and medium breakpoints

**Font-weight**
- [x] captions to read as sentences

**Name-value alignment**
- [x] captions to read as sentences

** TODOs **
- [x] Add key to nameValueListEditExample
- [x] Colorswatch Box "as='span'"
- [x] Missing healthy icons
