### ISSUE TITLE
Banner Notifications swarm

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#2352]
Goal: get teams consuming from Figma and grommet ASAP.

## Tasks
- [x] review existing design work from Kenny and other teams
- [x] pick a design direction, stay simple to start with
- [x] evaluate grommet's `Notification` component

## Deliverables
- [x] Figma component
- [x] any enhancements needed to grommet's `Notification` component
- [x] Design System site guidance and examples

**Comment by vavalos5** [comment]
I think this is pretty much done from designer and devs side. Will leave in review until tomorrow incase any last changes arise.

Figma file with guidance can [be found here](https://www.figma.com/file/FGvOd2htjrChVVS2oz73ds/HPE-Notifications?node-id=3066%3A9280).

**Comment by vavalos5** [comment]
@britt6612 & @taysea are you two ok if I close this?

**Comment by vavalos5** [comment]
donezo
