### ISSUE TITLE
Page Header

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#2368]
### **Explorations:**

- [x] grommet/hpe-design-system#2353 
- [x] grommet/hpe-design-system#2406 
- [x] grommet/hpe-design-system#2404
- [x] grommet/hpe-design-system#2424 
- [x] grommet/hpe-design-system#2431 
- [x] grommet/hpe-design-system#2449 
- [x] grommet/hpe-design-system#2480 
- [x] grommet/hpe-design-system#2517
- [x] grommet/hpe-design-system#2531 

### **Ideations:**

- [x] grommet/hpe-design-system#2393 
- [x] grommet/hpe-design-system#2536 
- [x] grommet/hpe-design-system#2542 
- [x] grommet/hpe-design-system#2555 

### **Implementations:**

- [x] grommet/hpe-design-system#2500
- [x] grommet/grommet#6090
- [x] grommet/grommet-theme-hpe#248 
- [x] grommet/hpe-design-system#2549 
- [x] grommet/hpe-design-system#2562
- [x] grommet/hpe-design-system#2557 
- [x] grommet/hpe-design-system#2602
- [x] grommet/hpe-design-system#2603
- [x] grommet/hpe-design-system#2604
- [x] grommet/grommet#6148

### **Research.**

- [x] grommet/hpe-design-system#2444 

### **Feedback:**

- [x] grommet/hpe-design-system#2394 
- [x] grommet/hpe-design-system#2405 

### **Validation**
- [x] Test PageHeader with Brittany & Mike

**Comment by ericsoderberghp** [comment]
The site selector comment came from Edgar. He's got designs to illustrate it.

**Comment by vavalos5** [comment]
> The site selector comment came from Edgar. He's got designs to illustrate it.

I'm not sure I understand your comment  @ericsoderberghp

**Comment by halocline** [comment]
I believe "Site selector" is equivalent to selecting a region representing a large data center, such as "US West (California), US West (Oregon), US East (Ohio), US East (Virginia)". This would serve as primary context for everything you are viewing within an app. When one of these sites is selected, all information presented throughout the app would be only relevant to that site.

This is similar to how the logged in user is a primary context for an app. All information presented to them would only be relevant to their company, their role, and their permissions.

**Comment by vavalos5** [comment]
how can we press down the styling of the PageHeader if stakeholders need more space before the fold
Is there a need for this?

**Comment by ericsoderberghp** [comment]
One of the ideas discussed in the office hours was whether it could be incorporated into the Page Header in some way, to remove the need to push content down.

**Comment by vavalos5** [comment]
@ericsoderberghp Yes, i'm a little hesitant to include the site selector use case after some chats with Edgar previous to me being OoO if the idea is to change where it lives at the end of the year.

Edgars comments:

"Here are three things to consider:  The first two are from our unified private cloud designs for March demo and June-Sept production.  The first is our "homepage", and the second is an example of what the user would see if they were to click on the "Virtual Machines" button in the navbar on the first.  But, there are drawbacks to this hub/spoke approach.  We want the entire app suite to be subject to a single site selector -- so that, no matter where/how you navigate, the selector is global and applies both for forward and backward navigation.  To that end, I am working on a NorthStar concept for UPC inside of GLCP.  A year from now, we should not need to have many stacks of headers like we have today (e.g. the first example has three headers - yuck).  So, I am ignoring current constraints and dropping down to a single header at the highest level and placing a site selector there.
![image (27)](https://user-images.githubusercontent.com/62117454/160021402-07f43925-b6f3-4a41-a483-cf471e0aa270.png)
![image (28)](https://user-images.githubusercontent.com/62117454/160021403-3bc3fd5f-eaf6-4eca-bc29-d131bdfb0ff6.png)
![image (29)](https://user-images.githubusercontent.com/62117454/160021404-9ca068a0-5679-40eb-9866-d48f36ccc84c.png)


It is based on the AWS experience:"
![image (30)](https://user-images.githubusercontent.com/62117454/160021297-02222a8a-a7ec-47a7-847b-ca8fd083dd49.png)

**Comment by ericsoderberghp** [comment]
Finally, well done all!
