### ISSUE TITLE
Card - Create a taxonomy which defines card types and the user purpose(s) they serve

### ISSUE THREAD

**Issue by SOjaHPE** [grommet/hpe-design-system#2584]
Important to organize and classify different types of card and features based on the similarities and differences of the concepts behind their usage. Goal is to figure out the different card types, see if we can **come up with a meaningful categorization, what their purpose is, name them appropriately to aid w/ how cards are documented** and drive the figma component work.

-------------------------

**Design Challenge**

With the overall [Card problem statement](https://github.com/grommet/hpe-design-system/issues/2462#issue-1174095873) in mind, create a taxonomy defining card types and the user purposes they serve so that they are named and aid how cards are documented.

**Tasks/Deliverables**
- [ ] Get Chris and Shawn's platform and .com thoughts and decision tree
- [x] Define card, its purpose and usage
- [x] Draft card "principles"
- [x] Enumerate and group the types of user problems designs are currently leaning on cards to solve
  - [x] Identify any instances of designs using Cards in an anti-pattern (i.e. used in ways that do not fit the definition of "card" or its principles). If possible, provided suggested alternative approach.
- [x] Create taxonomy which:
  - [x] Defines card types and user purpose(s) they serve
  - [ ] Informs anatomy and behaviors

**Comment by halocline** [comment]
In the spirit of trying to become more outcome oriented, may I propose that we re-name this issue as "Card - Define card types and the user purposes they serve"? Or ""Card - Create a taxonomy which defines card types and the user purpose(s) they serve"?

That way it is clear from a high-level I know that at the end of this issue I will have:
1) A list of user problems cards help solve (why cards exist)
2) Types of cards mapped to the user problem they solve (card category/name associated their use and purpose)

**Comment by SOjaHPE** [comment]
@L0ZZI  and Shawn Shultz from .com can provide their input with this exercise from a Platform and .COM perspective.

**Comment by taysea** [comment]
Working file: https://www.figma.com/file/W5QNddrUuFWcwLSVUJrRPd/Card-Exploration-and-Best-Practices?node-id=0%3A1

**Comment by taysea** [comment]
Closing, follow-on work is tracked in #2607 and #2608
