### ISSUE TITLE
Menu - Add the ability to group items

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#2621]
When there are more than a couple of items in a menu and the items could be grouped to aid understanding them:
- how should actions be grouped?
- how should that grouping be indicated? separator, text heading?

## deliverables

- [x] [problem statement for this issue](https://github.com/grommet/hpe-design-system/issues/2621#issuecomment-1146373069)
- [x] [guidance on action grouping, group taxonomy, ordering of groups and items within groups, examples](https://github.com/grommet/hpe-design-system/issues/2621#issuecomment-1146378788)
- [x] grouping API for the Menu component (https://github.com/grommet/grommet/pull/6162)
- [x] [visual indication of groups](https://github.com/grommet/hpe-design-system/issues/2621#issuecomment-1146382004)
- [ ] Add to Design System site menu item grouping and ordering guidance and examples #2636

## possible grouping examples

- state changing actions: enable/disable, power on/off
- transformational actions: edit, access
- transfer actions: share, download
- dangerous actions: delete
- navigation

## possible Menu api

`Menu items={[[item1, item2], [item3, item4, item5], [item6]]} />`

## possible grouping indicators

- horizontal rule separating the items
- heading text

**Comment by ericsoderberghp** [comment]
![Screen Shot 2022-05-31 at 10 07 15 AM](https://user-images.githubusercontent.com/11637956/171232865-610645c5-e9ff-4242-b838-df0e24ad9e1b.png)

**Comment by halocline** [comment]
**Problem Statement**

As a technical professional, I am responsible for configuring my environment, performing actions on resources in my environment, and occasionally sharing attributes about my environment such as sharing or downloading data.  

With a wide variety of configuration and executable actions, which may vary by resource type, I need easy access and ability to quickly find the action I desire among many possible choices, so that I may work confidently and efficiently.

**Comment by halocline** [comment]
[Working file](https://www.figma.com/file/gLToOyvAMDQ2JmaHQTtwTc/Menu---Grouped-Items?node-id=0%3A1)

**Comment by halocline** [comment]
**guidance on action grouping, group taxonomy, ordering of groups and items within groups, examples**

### Organizing menu items

Allow a user to quickly locate the menu item they desire by organizing menu items through thoughtful ordering and grouping.

**  Guiding principles**
- Make it easy for the user to scan by grouping related items and placing more frequently used actions at the top of the menu.
- Ensure intentionality, by placing destructive actions in a distinct, consistent location at the end of the menu.

**Grouping**
Group related menu items. Use separator lines to create visually distinct groups of related menu items.

Create separate groups for menu items initiating actions and items setting attributes. Menu items become unpredictable when the behavior of grouped items varies.  

Grouping may not be necessary when the number of menu items is small or when the items are naturally grouped by the menu’s context.

**Ordering**
Frequency of use should guide the order in which menu items are presented. Place the most frequently used items atop the menu. This anticipates what the user is looking for and allows them to locate the item as their eye scans the items top to bottom.  

When menu items are grouped, order items within that group by frequency. Additionally, place the most frequently used group at the top of the menu.

Exception: Dangerous or destructive actions altering a state which cannot be recovered, such as delete, should be placed as the last item in the menu with a visual separator for the dangerous actions grouping so that they are distinct from all other actions.

**Dangerous Actions **
Separate dangerous actions into their own group.

Any dangerous action should lead to a double confirmation.

**HPE Applications**
 Many HPE applications provide the ability for customers to configure, modify, and act upon resources in their environment.  

For applications in this context, groups of menu items can be thought of as:
- Configuring - Allow the user to set and modify attributes of a resource.
- Executing - Allow the user to act upon that resource.
- Transferring - Allow the user to share data related to that resource (e.g. download, link, sharing).

As example, a menu for a given resource might contain the following items within each of these groupings: 

Configuring:
- View [resource] details
- Edit [resource]
- Add [item] to [resource]
- Remove [item] from [resource]
- Assign [resource] to [another resource]
- Add [resource] to group

Executing:
- Launch [resource]
- Power on/off [resource]
- Reset [resource]
- Update/upgrade software/firmware version for [resource]

Transferring:
- Download [resource] data
- Share [resource]
- Send [resource] to [user]
- Notify [user] about [resource]

**Comment by halocline** [comment]
**visual indication of groups**

- use a horizontal line separator between groups
- a group heading may be added, but after reviewing the current HPE use cases, menu lengths are limited (as per best practice) and the context is sufficient, not necessitating headings at this time.
- group heading implementation evaluated in (https://github.com/grommet/grommet/pull/6162) but decided not to implement until use cases were more evident

**Comment by halocline** [comment]
Examples: 
![Screen Shot 2022-06-03 at 3 33 18 PM](https://user-images.githubusercontent.com/1756948/171957561-48d98d35-f2dc-4b00-8b92-3d3ff683f6dd.png)

![Screen Shot 2022-06-03 at 3 33 46 PM](https://user-images.githubusercontent.com/1756948/171957573-104a28d1-5347-4752-9ec9-d4d0d8ee243d.png)

![Screen Shot 2022-06-03 at 3 33 10 PM](https://user-images.githubusercontent.com/1756948/171957580-911cd9d6-d22a-4cbb-aea3-cc2d81270c06.png)
