### ISSUE TITLE
New HPE Brand Evaluation

### ISSUE THREAD

**Issue by SOjaHPE** [grommet/hpe-design-system#2719]
**Background**
The HPE design system functions as the single source of truth with regards to driving a consistent User Experience (UX) across HPE's GreenLake Platform portfolio of services and aspects of the HPE .com experience. The work of the Design System team maintains a set of UX patterns, interaction behaviors, behaviors, standards and guidelines and UI components which should always reflect that latest essence of HPE brand and marketing.

**Problem Statement**
Recent changes to the HPE Branding playbook for the 2022 Discover event will insert a delta into the known branding or what is defined as being 'On Brand'. Proposals for our evolving branding recipe book were put forth in the latest Discovery event but where this guidance lands is unknown since a round of feedback from Customers and Products need to be taken into account before decisions are definitive and final. Some proposed changes may be limited to impacting marketing oriented customers, or towards our Platform service users and in some cases patterns will apply to both, the work will be defining the boundaries.

**Challenge**
How might we collate the appropriate collateral material to review and assess the impacts of the new HPE Branding and Marketing guidance through the lens of the Design System design patterns, the guidance site, UX and UI toolkits.

**Success Criteria**
Bring clarity to this topic, provide a sound vision, roadmap to updating deliverables and a story synched up with HPE Marketing, GreenLake Platform Products and Servies and Brand Central which our documentation can be updated to remain the single source of truth across HPE.

**Tasks**
* [x] Make sure we the Design System team have something to evaluate (collateral to review) 
* [x] Design System team to review changes and identify any concerns, "here is how we’d like to approach it", let's have a conversation from here with the changes.
* [x] Organize a meeting with stakeholders, @ericsoderberghp , @SOjaHPE , @L0ZZI , @bahriaditi , @halocline , @taysea &  Shawn Shultz

**Comment by halocline** [comment]
This should be a swarm effort. I am happy to shuttle along the process. If you have desire to contribute during this sprint, please indicate so in this issue.

**Comment by taysea** [comment]
@halocline can this be close?

**Comment by halocline** [comment]
Closing. Per Chris's message, shareout with Brand received approval for the proposed work and recommendations made.
