### ISSUE TITLE
HPE brand refresh

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#2742]
Big Thing to track responding to the latest HPE brand refresh.

**Audit**

- [x] grommet/hpe-design-system#2773
- [x] Brand Refresh - document a list of things we’d like to push back on and discuss further --> Documented in 2773 here: https://github.com/grommet/hpe-design-system/issues/2773#issuecomment-1200066831
- [x] #2794
- [x] #2806
- ~Brand Refresh - audit writing style guidance from brand and compare to Design System~

**Explore**
- [x] grommet/grommet-theme-hpe#262
- [x] grommet/hpe-design-system#2779
- [x] #2793
- [x] grommet/hpe-design-system#2774
- [x] grommet/hpe-design-system#2775
- [x] #2801
- [x] #2803
- [x] #2821
- [x] #2815 

**New Assets**
- [x] Brand Refresh - add HPE GreenLake badge to AWS CloudFront bucket (where MetricHPEXS fonts and Design System video are stored)
- [x] Brand Refresh - add new brand gradients and textures to CloudFront bucket
- [x] #2824

**Test**
- [x] Brand Refresh - apply HPE theme to GreenLake Platform and evaluate impacts
- [x] Brand Refresh - apply HPE theme to Compute and evaluate impacts
- [x] Brand Refresh - apply HPE theme to Ezmeral and evaluate impacts

**Synthesis & Alignment**
- [x] #2822
- [x] #2823
- [x] #2871
- [x] #2872
- [x] #2873
- ~Brand Refresh - compare notes with Shawn Schultz~
- [x] Brand Refresh - share synthesis with Brand team

**Implementation**
- [x] https://github.com/grommet/grommet-theme-hpe/issues/275
- [x] #2937
- [x] #2938
- [x] #2939
- [x] #2940
- [x] #2969
- [ ] Brand Refresh - update guidance and examples as appropriate to new features and modified treatments
   - [x] Add guidance for CTA buttons vs primary action buttons
   - [x] Add guidance on new distinctive brand assets: https://github.com/grommet/hpe-design-system/pull/2951
   - [ ] Create examples and guidance on how to use mixed heading weights
   - [ ] Add guidance on accessibility considerations for gradients and textures

--------------------------------

- [x] Original issue - grommet/hpe-design-system#2719

**Comment by StingRay005** [comment]
Recording of this discussion available [here](https://hpe-my.sharepoint.com/:v:/p/kamlesh_thakur/EXNaS0dXcaZBgNB0V2motFEB3A3y5BCqd-eygjtn-UHmiw)
 

**Summary & next steps**: 

Goal is to collect all the big next steps 

**Expected deliverables**: 


- Updated guidance on DS site, with coordinated linkage to brand stuff (Rachael) - document how it relates to their product/BU/team (Brand Central currently has minimal guidance on this)  

- [ ] Likely Figma updates (on the design side of things) & examples (themes) on the DS site (including copy) 

- [ ] Communication: Announcement(s) highlighting the tie-ins 

- [ ] From a DEV standpoint, implementation approach needs to be sufficiently discussed, hasn't been discussed in detail yet – needs to align with the DS guidance (goal being to clarify when to use what) 

- How do we get there:  

- [ ] Two pieces to it  

- [ ] Through audit & analysis  

- [ ] Taylor & Matt going through Chris's new brand direction (and leveraging the adoption scorecard) 

- [ ] Mike K looking at this inside out from grommet side (such as buttons and layout changes) 

- [ ] Get Chris's perspective of Rachael's research on brand refresh 

- [ ] A final synthesized report out of some sort so we (DS team) can assess viability / feasibility 

- What we have been doing thus far – is reviewing Chris's research on brand refresh 

- [ ] This research we're basing our reviews on, could be dated 

- [ ] Historically, non-negotiable components have been approved by branding given use cases provided by Chris 

- [ ] Rachael needs more context in terms of aligning brand guidelines with dotcom  

- [ ] We need to review what Shawn has on this, and compare notes with Rachael's research  

- [ ] Implementation plan for dotcom is still TBD 

- Align John Vargas's team with Rachael's team – <Owner TBD> 

- These next steps outlined above are heavily reliant on the outcome of the audit and brand's concurrence with it – efforts may vary based on these 

- Minimal Effort Best Case: 

- [ ] Brand accepts themes/layout/Figma as is with minimal tweaks (2 weeks ish effort) 

- Worst case scenario: ? 

- [ ] Should we get extensive feedback from Brand, this effort could be significantly higher 10X 

- Interviewing Brand / Probing on: 

- [ ] Brand's typography guidance beyond colors for instance (yet to ask Brand – @taysea) 

Eric: 

- We should go to the discussion with recommendations of our own while emphasizing why we are recommending so

**Comment by StingRay005** [comment]
Tue Aug. 9, 2022 

 

Recommendation:  

- [ ] Ship CTA button to the enterprise app & review with Brand 

- [ ] Include nice to haves: E.g: Gradients & texture – visual treatment  

- [ ] Reference <test> section in the GitHub issue  

- [ ] Apply changes onto the DS site first (Matt's recommendation) 

External dependencies: 

- [ ] Discussion on colors (typography is more or less straightforward, in terms of options for fonts) 

- [ ] Should Gina / Melanie's team be directly involved? TBD 

- [ ] Chris not a decision maker (Stacey?) 

- [ ] Derek just needs to be informed 

Who owns deliverables / updates to the Figma – TBD 

- [ ] Pending items in explore section of the GitHub issue 

When can we have a synthesized plan to go take to brand? 

- [ ] In August sometime – TBD 

- [ ] This is when we'll be able to compare notes with Shawn S (Synthesis described above needs to be done by then first) 

Header/footer will be a Figma component – badge addition (prior to the synthesis of the audit) 

No follow up meeting needed post Eric's return from vacation – since we're making good progress here

**Comment by ecircenis** [comment]
Can we get guidance on when to include the element in a CTA vs when not to?  Brand seems to define CTA very differently from Product.  For example, in a delete confirmation dialog, the "Delete" button is a CTA Ii.e. primary button) and it seems inappropriate to pair the element with words like delete, remove, disable, etc and merely silly to associate it with words like create, apply, etc.  It seems as though our use of primary buttons should not change much except for rounding.  True or not?

**Comment by ecircenis** [comment]
Are we doing anything about the font so that lowercase i, uppercase I, and lowercase l can be distinguished one from another? Reading comprehensibility suffers with the current font. 
![image](https://user-images.githubusercontent.com/17883783/183774396-b47cf006-5fad-41f2-aa54-7fc1c67d49ab.png)

**Comment by taysea** [comment]
@ecircenis We have had some internal discussions along similar lines/shared thought about the buttons -- that the element in a CTA is more relevant for certain marketing-type use cases and less appropriate for platform use cases where we are just aiming to highlight a primary action. We will be refining our thoughts there and discussing with brand, and use cases like yours mentioned fall into the bucket of things we have discussed internally.

re: font, that is being tracked in this [font issue](https://github.com/grommet/hpe-design-system/issues/2080). There is a portion of the issue which is related to general typography guidance/anti-aliasing (elaborated by @halocline in this comment: https://github.com/grommet/hpe-design-system/issues/2080#issuecomment-1152623325). However, Matt do you know if there are any other font file resolutions being worked on?

**Comment by halocline** [comment]
Work has been completed
