### ISSUE TITLE
Figma -Looking at detached components in Figma Analytics to prioritize which one to start working on

### ISSUE THREAD

**Issue by bezAdane** [grommet/hpe-design-system#2745]
As a continuation of #2688, 
1. which components are being detached/broken
2. Going to stakeholders to get a better understanding of why they're breaking them.
3. Ask which component they'd benefit the most and why as a continuous effort of recreating components in Figma

Prior to this, a plan should be put in place on how we might tackle this due to all the components we have. 

**Todo’s** 

1. Continue gathered screen shots of which component has being detached/broken Figma analytics on all of our components from A-T are
2. Continue analyzing the rest of the components and go through files of where components are being detached. Finally, grab screen shots of those, the link of where the detached component lives and create a quick summary of what is wrong
Continue collecting the most commonly detached components.
 

- [x] **Need to be analyzed:** 

 Notifications
 PageHeader
Radio Button Group
RangeInput
Search
 Select
 Stack
 Tabs
 **Text Area**
 **Text Input Tip**
- [x] Meeting with Syliva and Geetha to get a better understanding of why they're breaking them, ask which component they'd benefit the most and why as a continuous effort of recreating components in Figma we would like to prioritize it.  
- [x] Based on the meeting and understanding from stakeholders have a meeting with Kenny for some recommendation of the first 3-4 component to prioritize to work on.Here are some recommendation of the first few components to prioritize work on.

These priority list came about after understand which components are used often through out the organization and  why the need for the component to be detached or even being created like (button, Cards, List ,Menu). Some reasons are either we are not flexible for some of the use cases  they have; Examples like  Card are organic component compare to icon, spiders those can be live anywhere. It’s composed by so many small atomic level and anyone can have diff approach. Another example is Buttons its used in a lot of different components and it was also important with the new branding update. We also decided the top priorities based on 80% of the component that are often used by our stakeholders.

1. Button
2. Menu
3. List
4. Tooltip
5. Cards
6. Table

**Comment by bezAdane** [comment]
I have a few detached/broken components I have not completely finished to close this ticket. Should be done end of day Monday.

**Comment by bezAdane** [comment]
Closing this ticket, The Figma analysis components/ meeting diff. organization and feedback gave us in site and direction on Prioritizing the new components to be built #2482
