### ISSUE TITLE
Toolbar - Documentation and best practices

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2769]
This ticket is to advance the design contribution from the Ezmeral team. 

**Tasks include:**

- [ ] Capture notes on best practices identified by their team (DS in collaboration w Geetha)
- [ ] Create first draft of documentation
- [ ] Share with stakeholders from other teams to capture any further feedback
- [ ] Make separate tickets for publishing this on Grommet, our site and Figma.

**Comment by taysea** [comment]
Closing, have published Toolbar/Data+friends patterns to site and Figma: https://design-system.hpe.design/components/data?q=data
