### ISSUE TITLE
Brand Refresh - add Button kind for element, shape, animation

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#2774]
Add two kinds of CTA button:
- [x] kind --> cta-primary
- [x] kind --> cta-alternative

Each kind should include:
- [x] border radius rounding
- [x] color (background + font + element)
- [ ] explore a subtle, tasteful animation within the element either on hover state: https://github.com/grommet/hpe-design-system/issues/2815

Other:
- [x] Pull request should be submitted against grommet-theme-hpe NEXT branch
- [x] Issues created for recommended enhancements to Grommet, for example:
  - [x] Button - ability to specify a default buttonKind icon to use via theme: https://github.com/grommet/grommet/issues/6271
  - [x] Button - ability to specify differing padding when icon only button: https://github.com/grommet/grommet/issues/6272
  - [ ] others???

**Comment by taysea** [comment]
cta-primary and alternate have been added to "NEXT" branch of theme https://github.com/grommet/grommet-theme-hpe/pull/263
