### ISSUE TITLE
Data - evaluate grommet API surface

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#3024]
Evaluate the API surface of the `<Data />` component for potential future features.

## Tasks

- [ ] evaluate whether we see blockers in growing to support selection + actions eventually
- [x] evaluate whether we see blockers in growing to support navigation, stuff like `onClickItem` and `onClickRow`
- [x] evaluate whether we see blockers in growing to support named filters, perhaps tied to the server side API above as well

**Comment by ericsoderberghp** [comment]
Current plan is to not wire up `Data` for navigation aspects. The DataTable case requires a choice between row level interaction and cell level interaction.

**Comment by ericsoderberghp** [comment]
For DataTable column selection and ordering, contemplating `<DataTableColumns />` as something that can be inserted inside the Toolbar. It would do the column selection and ordering as already designed.

**Comment by ericsoderberghp** [comment]
For named filters, contemplating allowing a controlled component that passes in an object that has:
```
{
  name: '',
  filters: { key: [value, ...], ... },
  search: '',
  columns: [name, ...]
}
```
Then `<Data filters={} onFilters={} />` that takes and provides the object above.
Combine this with `<DataNamedFilters options={[]} onChange={} />` to allow the user to choose from pre-built options and add and remove options.

**Comment by ericsoderberghp** [comment]
We have a good plan after reviewing.

**Comment by ericsoderberghp** [comment]
## Notes from evaluation work

- simplify using for navigation [no, rely on existing DataTable and List mechanisms]
	- could have onClickItem at Data level automatically wire up to DataTable.onClickRow and List.onClickItem
- selection + actions [rely on DataTable select , consider ButtonBar for actions]
	- Need to allow caller to pass in initial selection
	- How will it be controlled?
		- <Data select={[]} onSelect={() => {}} /> /* preferred */
		- <Data><DataTable select={[]} onSelect={() => {}} /></Data>
		- <DataSelection value{[]} onChange={() => {}} />
		- including outside of DataTable/List makes it easier to swap those two without having to wire up as much
	- How will it be consumed by actions?
		- custom hook? /* preferred */
			- import { useDataSelection } from 'grommet';
			  const select = useDataSelection();
			  <Button label="Disable" onClick={() => {... select ...}} />
		- context?
			- const select = useContext(DataSelectionContext);
			- const { select } = useContext(DataSelectionContext);
			- const { select } useContext(DataContext);
			- <Data>
			  {() => {
			     const { select } = useContext(DataContext);
			      return <Button label="Action" onClick={() => {... select ...}} />;
			  }
			  </Data>
		- caller managed via useState? /* always possible */
			- const [select, setSelect] = useState([]);
			  <Data select={select} onSelect={setSelect}>
			    <Button onClick={() => {...select...}} />
			  </Data>
- column ordering control + drop
	- add DataTableColumns for inclusion in Toolbar
	- allow DataTable.columns to separate whether to include from how to include
		- <DataTable columns={[<all possible>]}
	- <Toolbar><DataTableColumns options={[<all column names>]} value={[]} onChange={() => {}} /></Toolbar>
- should datum property rendering functions be pulled up to Data?
	- would allow filter label and column header label to be consistent
	- would allow further leveraging across DataTable/List/DataCards
		- rocket.name
	- maybe styles will be different enough to not warrant /* agreed */
	- spell out the details of what this would look like
