### ISSUE TITLE
Button - post submit busy indication -  Dev Implementation

### ISSUE THREAD

**Issue by Keeth-HPe** [grommet/hpe-design-system#3090]
[Figma File](https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=667%3A385&t=cFXJLDyDjS4GVEER-1)

## Tasks

- [x] publish a link with a few options for how to animate the Button, reachable from browsers, can be a pull request draft 
link to codesandbox: https://codesandbox.io/s/button-busy-indicator-forked-p4dy2v?file=/index.js
- [x] review with team
- [x] adjust to feedback
- [x] create a pull request for grommet with the final direction

## Acceptance Criteria

- [x] pull request created for grommet with the proposed implementation ready for review
Pull request: https://github.com/grommet/grommet/pull/6656

**Comment by taysea** [comment]
Friday 1/20 update:
- Set up preliminary version of animations: https://codesandbox.io/s/button-busy-indicator-zdscid?file=/index.js
- Planning to set up a share out on Monday or Tuesday to review with team and identify approaches we like / areas we'd like to alter or adjust

There are some technical considerations for how this will be integrated into Grommet / HPE theme that will need to be discussed. Once we have a slightly better sense of the direction for animation, I'll schedule a technical brainstorm with Eric/Matt/other interested devs to think about how to achieve this in a way that will make implementation easy. My goal is ultimately, someone building for HPE could do something like the following to Button and get the desired loading, but that will require some Grommet enhancements:

```
<Button label="Add application" loading={loading] primary />
```

**Comment by ericsoderberghp** [comment]
FYI, I'm amenable to enhancing grommet for this effort. I'm wondering if "busy" might be a better term than "loading". I'm also thinking the theme could drive the visual based on something like `<Button label="Add application" primary busy />`.

**Comment by taysea** [comment]
Notes from 1/23/22 shareout:
- Checkmark stroke width need to be thicker —> explore FormCheckMark
- Hover behavior shouldn’t show up when in busy state 
- Explore `aria-busy` and if it’s appropriate for this use case
- What do we do with the button label while in busy state? Should it disappear (see green bars flavor)? Persist (see other flavors)?
- Checkmark bounce is nice
- Bars might be a little too intense/loud
- We should also explore Chris’s latest ideations for a hover gradient state on primary buttons and see how that engages with the busy state (does it transition nicely, how do we make it feel like a cohesive language)

**Comment by ericsoderberghp** [comment]
Sorry to have missed the discussion. A few other thoughts after looking at the current sample:
- Maybe explore softening the animation entry a bit? The "Subtle looping ..." version feels like it has a nicer onramp, where it builds in. The other ones just jump right in to the full animation and it feels a bit abrupt.
- It would be nice to see how the API surface for users of Button would look and see it being used that way. I'm particularly interested in how the completion + checkmark + close layer would be handled and whether adding the checkmark at the end adds too much complexity for callers.
- The current animations for the first three bars examples feels like they are pulsing a bit, which seems like something is stuttering or broken. They also feel a bit too fast to me.

**Comment by jcfilben** [comment]
Update 2/24:
Wednesday I chatted with Scott and then Thursday I also connected with Betty. I feel I have some good suggestions from Scott and Betty I can explore. The plan is to get some more examples out in codesandbox and then share them with the designers for feedback.

**Comment by KennyAtHPE** [comment]
Initial reactions on current iterations:

- Green Bars
    - The animation starts off a bit suddenly, perhaps try incorporating a fade-in.
    - Not sure if we want to be changing the color of the text to black (how would this look in dark mode?) and whether or not it is still accessible with the flashing bars.
    - The checkmark at the end is too small

- Grey Bars
    - Prefer this one over the green bars but similar issues persist (animation being too sudden and the checkmark being too small)

- Subtle green bars
    - Accessibility concerns with the font color
    - Similar comments as above

- Subtle looping background fill
    - I really like this one, my only comment is that the checkmark is too small

- Ellipsis
    - Prefer this over the animations with the 'bars' however I think the previous animation is a bit better since "Add application" is still present
    - I would expect the checkmark size in this animation to be applied to the other iterations as well


Overall, my preference is Subtle looping background fill > Ellipsis >>>> animations with bars. I think the animation with bars is a bit too flashy/sudden and raises some accessibility concerns. The other two options seem like they would better fit my mental model when clicking on a button.

**Comment by jcfilben** [comment]
Ataching the link to forked codesandbox with latest iteration: https://codesandbox.io/s/button-busy-indicator-forked-p4dy2v?file=/index.js:4154-4299

**Comment by vavalos5** [comment]
I would completely agree with Kenny's comments above. My preference as well is the subtle ellipsis choice. Like Kenny mentioned, I do see accessibility issues with the changing bar colors as well as possibly being too much on the eyes with the movement.

**Comment by ericsoderberghp** [comment]
Of the options shown, I also agree with the ellipsis version being the most pleasing.

I'm wondering if we should play with a few variations on it still:
- Perhaps increase the size of the larger dots? I'm wondering if the current delta between the larger and smaller dots is too subtle.
- I recall @L0ZZI mentioning wanting to look for areas to inject a little more personality via subtle UI animations. To that end:
  - Maybe add a few more dots and time the animation to give them a bit of a "beat", for example 5 dots on a cha-cha beat, slow-slow-quick-quick-slow?
  - Maybe add a few more dots and do a slower rise left to right followed by a quicker retreat right to left?

However, I think that what we've got already would be sufficient for a first version. We could always refine further later.

**Comment by jcfilben** [comment]
@ericsoderberghp appreciate the feedback! I chatted with Vicky and Kenny this morning, and from that conversation there was a slight preference for the subtle looping animation over the ellipsis because with the subtle looping the label text is still visible. Maybe during the sprint demo we could show both options and see if we get any feedback from stakeholders?

**Comment by ericsoderberghp** [comment]
That sounds fine. I think the key aspect I wanted to convey was an extra attention to subtleties in the animation once a direction is chosen.

One thing I notice with the "Subtle looping background fill" option is that the first time it feels like a progress bar. So, when it gets to the end of its first progression, it feels like it is done. Then when it starts up again I feel like it's on its next progress bar, a bit like how Windows used to keep showing you multiple progress bars for things that had multiple steps.

I'm wondering if there's a way to keep with the concept of "background that allows the text to still be read" while feeling a bit less like a progress bar. Perhaps a single bar that wipes across? Avoiding the more visually complicated to process multiple bar options.

**Comment by jcfilben** [comment]
I agree with it feeling a bit like a progress bar. I'll play around with having a thinner bar that moves across the button and see how that feels.

**Comment by jcfilben** [comment]
I added a 'narrow looping bar' variation. I'm still making some adjustments to this variation. Right now I'm not feeling super strong about it but wanted to share what I had so far. https://codesandbox.io/s/button-busy-indicator-forked-p4dy2v?file=/index.js

**Comment by ericsoderberghp** [comment]
Thanks. I think it has slightly less of a progress bar feel. But, I think I still gravitate a bit more towards the "ellipsis" version.

**Comment by jcfilben** [comment]
I think since we keep getting the reaction of 'progress bar' from the other options we should just go ahead with ellipsis. The only concern with ellipsis is that the button label is no longer visible during the animation. However, I think for our intended use cases of the Button busy the period of time during loading will be pretty short, and the user will also still have the content of the page visible to give them context, with that in mind I think I would like to move forward with the ellipsis animation. Feel free to share any concerns, thoughts, etc.

**Comment by jcfilben** [comment]
Created a pull request with proposed implementation: https://github.com/grommet/grommet/pull/6656

**Comment by jcfilben** [comment]
Next steps can be tracked here: https://github.com/grommet/hpe-design-system/issues/3174
