### ISSUE TITLE
Data - design to create and delete views

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#3104]
We currently have the capability to pass a list of named views to Data and allow the user to select one of these views. This allows interesting combinations of filters to be combined into a "view", given a name, and then the user just pick that. You can see a simple example of this at: https://storybook.grommet.io/?path=/story/data-dataview-simple--simple

This ticket is to develop a design for allowing the user to create and delete their own views to suit their own needs. For example, if the user has a need to look at the data for a quarterly report based on status, they might want to create a view called "quarterly report" that filters down to the last 90 days and sorts by status.

## Tasks

- [x] review examples in comments below
- [x] ideate on some design approaches
- [x] review design approaches with the team
- [x] pick one

## Acceptance Criteria

- [x] chosen design created in Figma
- [ ] issue created for development work

**Comment by ericsoderberghp** [comment]
One example: https://www.figma.com/file/m8GfBvAVDpqwtfh1Sxod2T/CMAS-489---Saved-Filters?node-id=0%3A1&t=FZBOLfEdu3mreRk4-0

**Comment by Keeth-HPe** [comment]
@ericsoderberghp @SOjaHPE 

Thank you for the detailed description of the ticket, it is now well understood. I feel confident I can complete in 2 weeks.
 I've kick-started progress on this ticket. Will post the updates here in the thread.

**Comment by Keeth-HPe** [comment]
Sharing the file here :  Work in progress 🚧
https://www.figma.com/file/MS8yLFKERxEIrKKNNyvvvu/Data?node-id=2%3A10&t=dy4wM37JpCnJTjlM-1

@ericsoderberghp  @SOjaHPE

**Comment by ericsoderberghp** [comment]
> Sharing the file here : Work in progress 🚧 https://www.figma.com/file/MS8yLFKERxEIrKKNNyvvvu/Data?node-id=2%3A10&t=dy4wM37JpCnJTjlM-1
> 
> @ericsoderberghp @SOjaHPE

Good start. I've added some comments in Figma.

**Comment by Keeth-HPe** [comment]
@ericsoderberghp 
 Thank you for the early feedback. I read through all the comments.
 Jotting down the tasks here:
 

- [ ] Explore more use cases ( reach out to Greg & Ivan)
- [ ] Ideate flow 1: "Starting from an existing view and creating a new view with a variation on it."
- [ ] Ideate flow 2: 'save as a view' control within the filters
- [ ] Review

**Comment by Keeth-HPe** [comment]
Met with Vicky and Kenny. Noted few important feedback while on call : 

- [ ] Define the problem statement
- [ ] add research links/files and use cases
- [ ] Refine the walk through of the ideations.

- [ ] Review with the team.

**Comment by Keeth-HPe** [comment]
Adding the mind map here -  for save view and delete views. 

https://www.figma.com/file/GdKn0DIvqVTqg9Wu3A1iJq/Mind-Map-(Community)?node-id=0%3A1&t=Hydo2UiKHQwXHXLa-1

**Comment by vavalos5** [comment]
I did want to bring up another use cases that was shared with me from [GLCP.](https://www.figma.com/file/B52ssQxGpUV4KtrZoprQnu/Sustainability-Dashboard---February-2023?node-id=4033%3A158931&t=uWzDCbDrSnyIIG22-0) @ericsoderberghp @SOjaHPE I know we're pretty deep in the process and we may not want to consider this use case at the moment, but I did want to bring it to your attention.

**Comment by vavalos5** [comment]
Another [example](https://www.figma.com/file/uYPjyDakv565wvJ9BOy3nQ/Filter---Pricing-Request?node-id=131%3A2496&t=KuNkYYaSTMuil3OX-1) by GLC that was shared with us.

**Comment by Keeth-HPe** [comment]
Posting the Prototype link here: https://www.figma.com/proto/MS8yLFKERxEIrKKNNyvvvu/Data?page-id=0%3A1&node-id=249%3A136190&viewport=246%2C-362%2C0.04&scaling=contain&starting-point-node-id=83%3A56065

Had a review discussion with Eric and Scott 2 days ago, on the mind map that was created. The direction was set for save views and Manage views. Based on the insights  I've worked on the screens.  

Next week - Monday, I'd like to have another round of review. @ericsoderberghp  @SOjaHPE  :)

**Comment by Keeth-HPe** [comment]
@ericsoderberghp My apologies. This ticket was closed by mistake.

**Comment by SOjaHPE** [comment]
@Keeth-HPe reviewed your flow, a few questions
- the 'save as new view' flow looks good, I'm pondering what the right labels are for different actions. What you have is great, we can scrutinize those controls later on.
-  returning to the manage views dropdown after saving the view, that looked good. Simple and easy to follow
- The Add or View Select (drop down) flow - when i returned to the manage views flow, there wasn't any indication of what was the active 'current view' for the user. The select should indicate that, assumption the user is is still in the same session? Also, the view object trash cans 'remove' were displayed in that menu, intended only for manage flow as should showed previously..

![Image](https://user-images.githubusercontent.com/83719939/223160097-0a960b28-ff4a-4b97-8b95-9a01dda1ff57.png)

**Comment by Keeth-HPe** [comment]
Thank you for the feedback @SOjaHPE 

Replying to your third point :  
"The Add or View Select (drop down) flow" -   I wanted to show a default view. It is not a continuation of the previous flow. But I can add that flow as well.

 Yes my bad, I missed adding the delete in the previous flow. Added it now

**Comment by ericsoderberghp** [comment]
Nice progress! I've added a few comments. I think we're good to go to implementation for everything but the "manage views" modal. Getting close.

**Comment by ericsoderberghp** [comment]
Overall, this is looking good. I left a couple of comments in Figma, all in the context of "Manage views"

**Comment by SOjaHPE** [comment]
@Keeth-HPe Do you mind reviewing a sustainability dashboard 'save filter' use case that Sylvia has documented here:
[Sustainability Saved Filter Flow](https://www.figma.com/file/8pInYUjeKnr1fYH0ygpwC0/PAL--%3E-DS-proposal?node-id=120%3A17463&t=Z4dsoJFon72WrmdH-1)

It is an ask for the Glasgow release. They use a different location in the filters panel to manage their 'filters' views. Maybe document the differences between the two approaches managing views. We have a different terminology as well that should have alignment. Try to connect w/ Sylvia if you have any questions, gain access to the underlying page.

**Comment by vavalos5** [comment]
Update given by Scott:

This is the file where Keeth documented the differences in detail between Manage views & what Sylvia has.
https://www.figma.com/file/MS8yLFKERxEIrKKNNyvvvu/Data?node-id=511%3A112513&t=QQOfOSz4HYpJB72u-1
She said it was almost wrapped up. She don't think we need a follow up ticket. She wanted Eric and I to take a look into the differences.

She feels what we have is potentially a better direction. When compared to Sylvia's approach

**Comment by Keeth-HPe** [comment]
Documented the differences here and concluded the better approach. Requesting for review :) 
https://www.figma.com/file/MS8yLFKERxEIrKKNNyvvvu/Data?node-id=574%3A112179&t=QJxRSSDb8AFgTRqn-1

**Comment by ericsoderberghp** [comment]
Thanks. I've added some comments in Figma.

**Comment by Keeth-HPe** [comment]
@ericsoderberghp 
Thank you for the feedback, I added 2 flows (mindmap) in the file and the  rationale behind it the better option. Please share your thoughts. 

https://www.figma.com/file/MS8yLFKERxEIrKKNNyvvvu/Data?node-id=650%3A118374&t=4IjdDcqTLP7oEGfP-1

**Comment by Keeth-HPe** [comment]
Since we all agree on flow 1*, I believe this is good to go for implementation.  (Creating a new ticket for it)

*Flow 1 (In short) :

1. Click on the filter icon
2. Choose filters from the category
3. Apply filter
4. View filtered data
5. Click on “select or add view”
6. Click on ‘Save as a new view’
7. Enter the name
8. Save
9. Click on 'Manage views'
10. Select saved views to delete
11. Restore deleted views

Closing this ticket 🎉

@ericsoderberghp  @SOjaHPE
