### ISSUE TITLE
Design Tokens - exploration

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#3126]
## Tasks

- [x] research existing design token examples, structure, naming, technologies, scope
- [x] provide one or more alternative approaches, including grommet integration aspects
- [x] review with the team
- [x] create follow on tickets as needed

## Acceptance Criteria

- [x] research results and recommendations published as comments on this ticket
- [x] follow on tickets created as needed

## Initial notes

• Need to invest time looking into the solutions/approach for the creation of a central HPE DS token service to serve as the single source of truth pan HPE product/service teams since currently this is no single engineering solution. This is leading to individual token sets being defined across the several component frameworks being used.

**Look into** 
- CSS variables 
- W3C token spec

My ( @ericsoderberghp ) current leaning is towards creating a new repository under grommet called hpe-design-system-tokens that contains a single JSON file covering:

- color palette
- font sizes and line heights for t-shirt sizes
- content sizes for t-shirt sizes
- gutter sizes for t-shirt sizes

**Comment by KennyAtHPE** [comment]
#2777 related as well

**Comment by ericsoderberghp** [comment]
Exploring several aspects of tokens:
- structure of token space - currently leaning towards a flat of key/value pairs
- format of names - dot delimited "path" aspects, for example: "font.weight.bold"
- structure of names - stay flatter, resist too much hierarchy, names will discovered primarily via search
- format of values - simple strings or numbers, values should not need to be parsed in consumption
- scope of content - foundational atoms, no composition, exploring composition as part of a style system
- consumers - designers and developers, Figma, grommet styling, partner style systems

**Comment by ericsoderberghp** [comment]
Some resources related to color palettes:
- https://chartio.com/learn/charts/how-to-choose-colors-data-visualization/
- https://www.storytellingwithdata.com/blog/2020/5/6/picking-the-right-colors
- https://nightingaledvs.com/how-to-create-brand-colors-for-data-visualization-style-guidelines/

**Comment by ericsoderberghp** [comment]
3/28 update

- designers and developers are wrangling over the token naming structure.
- primary areas of focus are typography, color, spacing, breakpoints.
- current target is a Proof Of Concept share-out at the beginning of May.

**Comment by taysea** [comment]
4/7 Status Update:

Will connect with Eric on Monday for how to close out this ticket and file follow-on tickets. For "exploration", I feel like we are green to close this one out by end of sprint.

What was completed this week:
- Got the tokens repo working with grommet-theme-hpe branch and in process of filling in the tokens into the branch. Some initial takeaways --> grommet-theme-hpe uses tshirt strings as a way to then internally apply responsive styling. This conflicts with how tokens are already resolved to raw px values. Additionally, we still have to figure out how we want to handle light/dark modes in the token structure
- Exploring how to manage tokens centrally with a Figma plugin "Tokens Studio". The JSON format required for this plugin differs slightly from the flat structure we have in our repo. So we may to create some additional translation, which is doable. Kenny also mentioned a plugin he tried in the past with tokens was someone flaky/would crash so we should assess the reliability and maintenance of the plugin choice before investing too much time.

**Comment by taysea** [comment]
I made today on tokens pipeline:
- [Set up “stable” branch on hpe-design-tokens repo](https://github.com/grommet/hpe-design-tokens/tree/stable)
- [Consumed that in TOKENS branch on grommet-theme-hpe](https://github.com/grommet/grommet-theme-hpe/tree/TOKENS) and set up TOKENS-stable (token namespace is still evolving, so the actual “token” names being used will likely change. currently have only filled in the colors but will be adding the global tokens next)
- Put up [deploy preview on Design System site](https://github.com/grommet/hpe-design-system/pull/3270) that consumes the tokens version of grommet-theme-hpe

One technical note is that right now, hpe-design-tokens needed to be added as a dependency in the Design System site as well. Ideally, we could improve the build process of grommet-theme-hpe to resolve token values so teams don’t have to add another dependency.

**Comment by taysea** [comment]
Next steps:

Naming
- [ ] Iron out naming structure + creating updated tokens JSON to align with that (Taylor)

Figma-related
- [ ] Add build step in tokens that builds appropriate file for Figma to import (Eric)
- [ ] Demo applying tokens using Figma Tokens Studio plugin

grommet-theme-hpe
- [ ] grommet-theme-hpe build step to resolve token values so callers don't have to include hpe-design-tokens as a dependency in their projects (Eric)
- [ ] Apply all global tokens in grommet-theme-hpe (Taylor)
- [ ] Create preview of design system site using the tokens and demo (Taylor)

grommet-exp
- [ ] Build out Diane's design as POC for non-Grommet based implementations

Stakeholder share-out/engagement
- [ ] Broader share-out with stakeholders for feedback, input

**Comment by taysea** [comment]
Closing since follow on tickets have been filed.
