### ISSUE TITLE
Create SBOM and load into VTN

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#3128]
## Tasks

- [x] explain what these acronyms stand for and mean
- [x] generate and SBOM for Grommet in SPDX-JSON spec/format
- [x] load SBOM into VTN

## Acceptance Criteria

- [x] SBOM loaded into VTN

**Comment by jcfilben** [comment]
Got setup with the Code Insight tool which is capable of running scans and generating a SBOM in the format VTN requires. I setup the grommet project in Code Insight and ran a scan on the master branch as well as the v2.29.1 tag.
To generate the SBOM and import it into VTN I need to first create a distribution list that includes a manager account. I sent @SOjaHPE the details for requesting access. Once there is a manager account I can create the distribution list, then the SBOM and load it into VTN.

**Comment by jcfilben** [comment]
SBOM stands for software bill of materials. This is a list of the software behind a project. The list includes licensing and version information. Knowing each piece of software behind your project can be helpful to stay on top of security vulnerabilities and make sure you are compliant with licensing rules. More information can be found here: https://ntia.gov/page/software-bill-materials.

VTN is HPE's [vulnerability tracking notification application](https://vtn.hpecorp.net/). By uploading Grommet's SBOM into VTN we will receive notifications if any known vulnerabilities are found in our dependencies. Currently Scott and I are on the email notification list but I can add any other team members to the list if they are interested.

I generated Grommet's SBOM using the Revenera Code Insight tool, setup a notification distribution list, then uploaded the SBOM into VTN.

**Comment by SOjaHPE** [comment]
@jcfilben hopefully the system notified you that my VTN account was created. Let me know if there is any action items on me with regards to this.

**Comment by jcfilben** [comment]
> @jcfilben hopefully the system notified you that my VTN account was created. Let me know if there is any action items on me with regards to this.

I didn't get a notification when you created your account but I did see your account when I logged into the VTN and I was able to add you to the notification list for grommet. No action items needed from your end at this point.
