### ISSUE TITLE
review a GLCP pull request

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#3130]
## Tasks

- [x] scan GLCP pull requests https://github.com/glcp/frontend/pull for something that we should review. Look for something not customer visible, behind Launch Darkly, such as Location services.
- [x] coordinate with Eric to email their manager when we've selected a pull request
- [x] review one of the GLCP pull requests looking for any simple and helpful feedback we could give and add a review to it, focus on using grommet components well, more implementation focused than design focused

## Acceptance Criteria

- [ ] review submitted to one GLCP pull request

** NOTE: time-box this to about one hour of work **

**Comment by halocline** [comment]
Closing as @MikeKingdom has been consulting GLCP in this manner.
