### ISSUE TITLE
Data Components testing with Bill

### ISSUE THREAD

**Issue by britt6612** [grommet/hpe-design-system#3131]
## Tasks

- [x] create a simple outline of what we'd like to test
- [x] test new Data components in grommet with Bill
- [ ] document any accessibility issues uncovered
- [ ] create new tickets for follow on work

## Acceptance Criteria

- [ ] summary of issues uncovered documented as a comment on this issue
- [ ] new tickets created for follow on work

**Comment by britt6612** [comment]
https://storybook.grommet.io/iframe.html?args=&id=layout-data-list--example&viewMode=story
### Have Bill go to the DataList story view the list and get familiar with the List.

- Try searching Eric and see what is the output. 
- Clear the search and then try typing “z” what is the output?
- Was the search results clear and understandable?

### Use Filtering

- Filter by FortCollins
- was this clear that the filter was applied
- was the summary read our known
- clear the filter so the list goes back
- go back to filter pick 2 options
- how could we better communicate how many filters were applied

**Comment by britt6612** [comment]
Link to recording: https://hpe-my.sharepoint.com/:v:/p/jessica_cheyenne_filben/EfjxNcCBnM1ChuKL3ajtfFcBbHQvz9i60LdTbgcfEfIfgA

notes
Testing with Bill
Jessica asked Bill to navigate around.
Bill was expecting the screen reader to have said 1 result or 2. Or just how many results were retrieved but currently the component doesn’t do that.
Once he got into the list, he was able to find 1 item, so that was a clue to him that the search result was just 1 item. It wasn’t clear to him.
Jessica asked him to go back to search to clear the value (Eric), he cleared manually by using delete button.
Jesica asked him to search “Z”. Jessica let him know it resulted with no list items but that wasn’t clear to Bill. When he presses enter, it should tell him the amount of results, but nothing was output by the screen reader. He needed to navigate down to the “0 results of 8 items” to get a clue of how many items are available.
Next was to go to the filters button and interact with button to see what’s available within the button. Bill uses space or enter to open. He selected Fort Collins and applied filter using space bar. He had to press the down arrow key just to understand how many results were retrieved.  Jessica asked if it was read out the way she expected it. He felt it was good.
Second prompt was to select 2 filter this time. Bill selected Fort Collins and SF. This time he used Enter to submit selected items.
When applying filters, maybe there should be an aria label of how many filters are being applied.

**Comment by britt6612** [comment]
closing and made new issue for follow on work [here](https://github.com/grommet/grommet/issues/6630)
