### ISSUE TITLE
Page Templates - List + Table

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#3148]
[Figma file
](https://www.figma.com/file/4rdBkUlHd5MCVq3hvUOXHd/Page-Layouts?node-id=5639%3A166209&t=qRxjtBcYDfqAJ7A2-1)
## Problem Statement

How might we provide easy to use List/DataTable examples to our designers and developer so that they can copy and paste them when designing?

## Acceptance Criteria

- [x] publish List page template in a format consistent with the [home page template]()
- [x] publish DataTable page template in a format consistent with the [home page template]()

## Tasks

- [x]  create success criteria
- [x]  collect and review List/DataTable examples and understand what it entails [1 day max]
- [x]  gather List/DataTable examples from other teams like Storage and Compute [2 days max]
- [x]  V1 - ideate ideas on how to visually layout List/DataTable (skeletal to more detailed view ((examples)) [2 days max]
- [x]  connect w/ Taylor
- [x]  share + gather feedback from Scott + Eric
- [x]  implement feedback
- [x]  share + gather feedback from stakeholders
- [x]  implement feedback

## Notes

Scott and I connected on 2/13/23 to discuss the next steps following ticket #3123. This ticket is still TBD as a next step or next template we should work on.

**Stakeholders**:
Chris
Gina
Justin
Amanda
Diane?

**Comment by vavalos5** [comment]
From the use cases i've gathered, i've categorized the different types of list and datatable examples.  I've created a variety of different flavors of DataTable templates based off of common use cases.

In addition, Chris is using a different type of styling for lists. I've conducted research on how other frameworks are handling who have similar them styling as us. [I've created 2 examples to show some options here](https://www.figma.com/file/4rdBkUlHd5MCVq3hvUOXHd/Page-Layouts?node-id=5549%3A122416&t=O56byl6HIQY2PW3i-1).

I've also done some [explorations on how we might style vertical tabs ](https://www.figma.com/file/4rdBkUlHd5MCVq3hvUOXHd/Page-Layouts?node-id=5533%3A125029&t=O56byl6HIQY2PW3i-1)since many service teams have a need. I've added two options here using our button styling in one option and a second using tabs styling.

@ericsoderberghp @SOjaHPE When you have a moment, could you take a look and let me know if we're heading in the right direction?

I am also planning to set up a call with Chris on Monday to chat through these examples and discuss the variety of flavors.

**Comment by vavalos5** [comment]
Although this is not a part of this ticket, i've been exploring and working with Chris on identifying visual styling and behaviors for how we might style list items. This also includes the vertical tabs.

**Comment by vavalos5** [comment]
- New explorations for the [list items ](https://www.figma.com/file/4rdBkUlHd5MCVq3hvUOXHd/Page-Layouts?node-id=5549%3A122416&t=VA0uZu1m3l7rGOHE-1)styling 
- I can figure out behaviors after we decide on direction. 
- Chatted w/ Matt earlier on what our new brand radius styling is. I've been confused on whether to design with our current theme or future and he thinks we should be designing with our current components/t-shirt sizing radius since we don’t have that quite defined for the new brand styling. 
- Also added [2 other examples for tab](https://www.figma.com/file/4rdBkUlHd5MCVq3hvUOXHd/Page-Layouts?node-id=5533%3A125029&t=VA0uZu1m3l7rGOHE-1)s based off of what we Chris and I chatted on
- @ericsoderberghp @SOjaHPE Feel free to drop comments on Figma

**Comment by vavalos5** [comment]
This is also not a part of this ticket but some side convos i've had with Matt. 

@halocline @taysea would also like to [get your feedback on the following two](https://www.figma.com/file/4rdBkUlHd5MCVq3hvUOXHd/Page-Layouts?node-id=5581%3A175570&t=VA0uZu1m3l7rGOHE-1):

- recommendations/enhancements on top page padding and how I imagine automatically decreasing when getting into the smaller resolutions.
- bottom of the template spacing. I also included one of Chris's examples where he has list items and have added padding to give visual of how the padding will look like.

**Comment by ericsoderberghp** [comment]
I've added some comments. Nice to see the options and also in both background styles.

**Comment by vavalos5** [comment]
I've received comments from Matt, Taylor and Eric. I have implemented the feedback and ready for another review.

I have a meeting set up with Eric and Scott in a bit so will be getting feedback then.

**Comment by vavalos5** [comment]
After chatting with Eric and Scott this AM, i've made cleaned up and made changes to the [List/DataTable templates](https://www.figma.com/file/4rdBkUlHd5MCVq3hvUOXHd/Page-Layouts?node-id=5639%3A166209&t=wtWRHbRS6bTwR7Wq-1) by using real use cases. We have 2 flavors of each, note that I saw opportunities to add multiple items within the templates to avoid creating too many flavors.

Let me know your thoughts @ericsoderberghp @SOjaHPE

**Comment by ericsoderberghp** [comment]
Nice progress! I've dropped some comments in Figma.

**Comment by vavalos5** [comment]
Thank you @ericsoderberghp i've made most of the changes you've pointed out. I'm awaiting a response from Greg on the order of some of the columns as Amanda made me aware that that was a screen he worked on.

It was nice to get an initial reaction from Amanda on the template.

![Image](https://user-images.githubusercontent.com/62117454/221668213-b2d7939e-94be-4653-8aab-ac4ab4f3e97a.png)

Adding this to in review while I wait for Greg's response.

**Comment by vavalos5** [comment]
Greg's comment:
![Image](https://user-images.githubusercontent.com/62117454/221692488-505f391a-2fc4-4160-9056-0b8d0447b355.png)

Awaiting on Edgars comment.

Edgar's comment:

**Comment by vavalos5** [comment]
@ericsoderberghp Let me know your thoughts based off of the comments Greg and Edgar made. It sounds like the order of the items is really up to the service team. Let me know if I should make further changes.

**Comment by ericsoderberghp** [comment]
> @ericsoderberghp Let me know your thoughts based off of the comments Greg and Edgar made. It sounds like the order of the items is really up to the service team. Let me know if I should make further changes.

I'm OK with leaving the column order as you have it currently.

**Comment by vavalos5** [comment]
Perfect, closing as done! 🥳
