### ISSUE TITLE
PageHeader + Toolbar - exporting data

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#3169]
Add examples + guidance of when export button would appear at the pageheader or toolbar level to design system site

## Tasks

- [x] collect examples from existing services
- [x] consider both PageHeader and Toolbar contexts
- [x] consider whether the format should be JSON, Excel, or user selectable
- [x] consider whether to include this capability within Data Toolbar, perhaps "DataExport"
- [x] include in an example and guidance on the design system site

## Acceptance Criteria

- [x] recommended design shown in Figma
- [ ] example and guidance added to the design system site

## Notes

A couple weeks ago, Amanda and I worked on creating examples within some CMAS reports where there is an export button. Sylvia has asked if we'd be able to add these examples to the design system site where there are some scenarios where the export button might live at the page header level and others at the toolbar level.

Please see link where there are different examples for reference and add to design system site: https://www.figma.com/file/ZIINRBMdjrONUYNdv2RuqP/CMAS-412-Export-reports-and-tabular-data-in-CoM?node-id=1%3A3&t=k8zoELeqGTunm3la-1

**Comment by vavalos5** [comment]
GLCP: https://www.figma.com/file/8pInYUjeKnr1fYH0ygpwC0/PAL--%3E-DS-proposal?node-id=119%3A447&t=6sc8eFlJPc2Wcnx1-0

Other Common Cloud: https://www.figma.com/file/6ovDBTzn8ChEaTS9JmYctX/Audit-Log-V0.1?node-id=1194%3A47544&t=JMGZJDtHsJinoxeu-1

**Comment by vavalos5** [comment]
IF export button is meant to download a specific part of the page such as a group of clusters within a datatable, or a graph(s), THEN it should be at the datatable/graph/list level. 

IF export button downloads everything within the page (datatable + graph, just datatable within view, etc..), THEN it should be at the PageHeader level.

**Comment by vavalos5** [comment]
I've collected use cases [in this Figma file](https://www.figma.com/file/BHp0KrOcPvbnzNyshfHkd8/HPE-Page-Header?node-id=2426%3A40792&t=2KJudaRmljYtCNHd-1) where i've changed one of the examples due to me not agreeing to the placement of the buttons. @ericsoderberghp @SOjaHPE This is ready for a review. Thanks! :)

**Comment by vavalos5** [comment]
Chatted with Eric earlier and received feedback. Will be chatting with folks to further understand what happens when they select the "export button".

**Comment by vavalos5** [comment]
I've adjust examples + added guidance based on my conversation with Eric yesterday.

[Examples can be found here.
](https://www.figma.com/file/BHp0KrOcPvbnzNyshfHkd8/HPE-Page-Header?node-id=2426%3A40792&t=XnCUgxUwzGyhSKx0-1)
[Guidance](https://www.figma.com/file/BHp0KrOcPvbnzNyshfHkd8/HPE-Page-Header?node-id=2426%3A40792&t=XnCUgxUwzGyhSKx0-1)

ready for review @ericsoderberghp

**Comment by vavalos5** [comment]
2/10 Update: Awaiting for review from @ericsoderberghp

**Comment by vavalos5** [comment]
Eric has approved this ticket. The next follow on ticket before adding to the design system site is to work on ticket #2769 since we don't have the toolbar component on the site, this guidance would fall under this page.

**Comment by vavalos5** [comment]
#3214 follow on ticket.
