### ISSUE TITLE
Page Templates - Detail/ Object Views

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#3170]
Figma file - TBD

## Problem Statement

How might we provide easy to use Detail/Object view examples to our designers and developer so that they can copy and paste them when designing?

## Acceptance Criteria

- [ ] publish Detail page template in a format consistent with the [home page template]()

## Tasks

- [ ]  create success criteria
- [ ]  collect and review detail/object view examples and understand what it entails [1 day max]
- [ ]  gather detail/object view examples from other teams like Storage and Compute [2 days max]
- [ ]  V1 - ideate ideas on how to visually layout detail/object view (skeletal to more detailed view ((examples)) [2 days max]
- [ ]  connect w/ Team
- [ ]  share + gather feedback from Scott + Eric
- [ ]  implement feedback
- [ ]  share + gather feedback from stakeholders
- [ ]  implement feedback

## Notes

I've pinged Scott and Eric on 2/28/23 to ask which type of template we should work on next. This template is what we agreed on.

**Stakeholders**:
Chris
Gina
Justin
Amanda

**Comment by vavalos5** [comment]
[I've created a few different flavors of Detail views based off of the use cases i've gathered.
](https://www.figma.com/file/4rdBkUlHd5MCVq3hvUOXHd/Page-Layouts?node-id=5673%3A213574&t=3sJ5yxffV0Jo5rMy-1)
I've yet to collect use cases from storage but have plenty from compute.

Let me know your thoughts @ericsoderberghp @SOjaHPE any others that you feel we should include in the explorations? 

Thanks!

**Comment by ericsoderberghp** [comment]
Thanks for laying out the examples with comments. Three aspects that stood out to me:
- location and density of action buttons. In the Page Header, in a section Header, or in a Toolbar. I think all can be options, based on where the content the action is associated with
- structure and in-detail navigation. Tabs under the Page Header, sections of content, cards. I think all can be options.
- use of background coloring. I like showing the variations with background-back in exploration. I think our first details template should match our other templates for consistency in this area.

**Comment by vavalos5** [comment]
3/3/23 update - Based off of a chat I had with Eric earlier today, he mentioned we will want to go with the Name-Value Pair with actions and look into the horizontal/vertical tabs styling. I've got previous explorations on how we might want to style vertical tabs and will discussing those on Monday.

**Comment by vavalos5** [comment]
Awaiting on some context from Chris and Amanda.

**Comment by vavalos5** [comment]
I've adjusted the final example based on feedback received from Eric, [that can be found here.](https://www.figma.com/file/4rdBkUlHd5MCVq3hvUOXHd/Page-Layouts?node-id=5673%3A213574&t=ouOW9kiN5khwVtT5-1) Let me know @ericsoderberghp if there should be any other adjustment.


I've also added examples based off of me and Chris's chat on Wednesday. [Those can be found here](https://www.figma.com/file/4rdBkUlHd5MCVq3hvUOXHd/Page-Layouts?node-id=5673%3A213574&t=ouOW9kiN5khwVtT5-1) if we decided to go in any of these directions.

**Comment by vavalos5** [comment]
Eric has approved the designs I've created. Ticket is good to close. Those [designs can be found here](https://www.figma.com/file/4rdBkUlHd5MCVq3hvUOXHd/Page-Layouts?node-id=5765%3A217829&t=yp2Jw4y5NI0XxWu5-1) where you'll find the other templates created that are ready to be implemented.

**Comment by ericsoderberghp** [comment]
I would expect the design to be found here: https://www.figma.com/file/4rdBkUlHd5MCVq3hvUOXHd/Page-Layouts?node-id=5659%3A175504&t=nAVtBiDTbAb0l4QI-0

**Comment by vavalos5** [comment]
#3204 AND/OR #3205 can be the follow on tickets for this next sprint
