### ISSUE TITLE
Brand Refresh - scope Figma work needed to align

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#3175]
## Acceptance Criteria

- [x] itemized list of changes needed, sufficient to create issues down the road as needed

**Comment by vavalos5** [comment]
Is there a list of items changed or that will be changing on the design system site that has already been discussed/approved?

**Comment by taysea** [comment]
Hi Vicky, here are the diffs between the old theme and new version (you'll need to click on "expand diff" in hpe.js): https://github.com/grommet/grommet-theme-hpe/pull/310/files

I'm happy to make this into the itemized list since I'm familiar with all the changes.

**Comment by vavalos5** [comment]
Thanks @taysea maybe you can show me how I can see the differences and work on the itemized list together if you're freee?

**Comment by vavalos5** [comment]
03/03/23 Update - Taylor and I connected yesterday to discuss how to read the changes made to colors, text, components, etc.. within the PR. She is creating a list of changes fro me to revise and review to determine changes that need to be done in Figma.

**Comment by taysea** [comment]
Colors:
- [ ] Changed light mode `text-strong` to `#444444`.
- [ ] Changed light mode `text` to `#6F6F6F`.
- [ ] Changed layer overlay background to `#0000001F`.
- [ ] Changed `selected-background` to `brand`.
- [ ] Changed `selected-text` to `text-primary-button` (white, necessary to meet color contrast on HPE green background).
- [ ] Changed `control` to `brand`.

Accordion:
- [ ] Changed title to use heading `level: 3`.

Anchor:
- [ ] Changed color to `text-strong`.
- [ ] Changed weight to `bold` (700).
- [ ] For sizes large and greater, changed color to `brand`.

Button:

- [ ] Increased rounding on all button kinds and sizes from 2em (full rounding). The exception is toolbar buttons which retain the existing 6px radius.
- [ ] For medium buttons, changed padding to `6px` vertical and `18px` horizontal for buttons with labels and to `9px` for icon-only buttons to ensure a `36px` height.
- [ ] For small buttons, changed padding to `6px` vertical and `18px` horizontal for buttons with labels and to `9px` for icon-only buttons to ensure a `36px` height.
- [ ] For large buttons, changed padding to `8px` vertical and `24px` horizontal for buttons with labels and to `15px` for icon-only buttons to ensure a `48px` height.
- [ ] Removed border from toolbar button.
- [ ] Changed hover treatment of primary buttons to use a linear-gradient.
- [ ] Changed disabled treatment of buttons to use `opacity: 0.3`.
- [ ] Reduced size of `badge` to be more proportional with reduced icon sizes.

Calendar:

- [ ] Changed use of Heading to Text for proper semantic rendering of month and year.
- [ ] Changed use of `FormNext` and `FormPrevious` icons to `Next` and `Previous`.
- [ ] Changed selected day to have background `brand` and color `text-primary-button` (white, necessary to meet color contrast requirement on HPE green background).

CheckBox:

- [ ] Changed selected state to use `brand`.

DataTable:

- [ ] Changed heading cell weight to `500`.
- [ ] Changed primary key weight to `400` and color to `text-strong`.
- [ ] Increased pinned cell background blur to `12px`.

Heading:
The following are formatted as `font-size` / `line-height` / `font-weight`.

- [ ] 1: 36px / 36px / 
- [ ] 2: 24px / 24px
- [ ] 3: 20px / 20px / 500
- [ ] 4: 16px / 16px / 500
- [ ] 5: 12px / 12px / 600
- [ ] 6: 12px / 12px / 600

Icons:

- [ ] Changed sizing to align with font-size values: small (`16px`), medium (`18px`), large (`24px`), xlarge (`30px`), xxlarge (`36px`).
- [ ] Added `disabledScaleDown` which ensures for certain simple icons (Close, LinkNext, etc.) that the stroke does not scale down at smaller sizes which was creating undesirably thin icons.

Layer:

- [ ] Changed layer overlay background color to `#0000001F`.
- [ ] Added `blur(12px)` to overlay.

NameValuePair:

- [ ] Changed name color to `text-strong`.
- [ ] Changed name weight to `500`.

Notification:

- [ ] Changed weight to `500` and color to `text-strong`.

PageHeader:

- [ ] Changed subtitle to size `xlarge`.

Paragraph:
The following are formatted as `font-size / line-height / font-weight / max-width`.

- [ ] xsmall: 14px / 16px / 400 / 25em
- [ ] small: 16px / 20px / 400 / 25em
- [ ] medium: 18px / 24px / 400 / 25em
- [ ] large: 24px / 32px / 400 / 25em
- [ ] xlarge: 30px / 36px / 300 / 25em
- [ ] xxlarge: 36px / 40px / 300 / 25em

RadioButton:

- [ ] Changed selected state to use `brand`.

RangeInput:

- [ ] Changed color to `brand`.

RangeSelector:

- [ ] Changed color to `brand`.

Select:

- [ ] Changed selected state to use `brand`.
- [ ] Changed weight of selected option to use `bold` in order to meet color contrast requirement on HPE green background.

Spinner:

- [ ] Changed color to `brand`.

Tab:

- [ ] Changed color to `text`.
- [ ] Changed weight of active tab to `bold`.
- [ ] Changed border color of active tab to `brand`.
- [ ] Reduced border size of active tab to `medium` (4px).
- [ ] Added border color of `border-weak` on hover.
- [ ] Changed horizontal pad of tab to `18px` to align with Button.

Tabs:

- [ ] Added `alignSelf: “start”` to ensure bottom border under all tab controls is only under the tabs rather than extending across entire container.
- [ ] Reduced border size under all tab controls to `xsmall`.
- [ ] Changed border color under all tab controls to `border-weak`.

Table:

- [ ] Changed footer font-weight to `500`.

Tag:

- [ ] Changed value font-weight to `500`.

Text:
The following are formatted as `font-size / line-height / font-weight`.

- [ ] xsmall: 14px / 16px / 400
- [ ] small: 16px / 20px / 400
- [ ] medium: 18px / 24px / 400 (not changed)
- [ ] large: 24px / 32px / 400
- [ ] xlarge: 30px / 36px / 300
- [ ] xxlarge: 36px / 40px / 300
- [ ] 3xl: 42px / 46px / 300
- [ ] 4xl: 48px / 48px / 300
- [ ] 5xl: 72px / 72px / 300
- [ ] 6xl: 72px / 72px / 300

**Comment by vavalos5** [comment]
Thank you @taysea. I'll take a further look later this week.

@ericsoderberghp should we create individual tickets for these changes as a next step?

**Comment by vavalos5** [comment]
3/10 Update: Unsure if we should create subsequent tickets for each change needed or if we should leave this open. @ericsoderberghp

**Comment by halocline** [comment]
> 3/10 Update: Unsure if we should create subsequent tickets for each change needed or if we should leave this open. @ericsoderberghp

I would recommend creating subsequent issues which then could be tasked out to a variety of folks (e.g. Joelle, Ashley, Kenny, Vicky, ...).

**Comment by vavalos5** [comment]
I've reviewed the code and the list in here, looks good! Closing but will need your help @KennyAtHPE to create subsequent tickets for these. Will need to connect with Joelle and Ashley too on deviding these to create tickets. I've created a follow up ticket #3201 so we don't forget next steps of what is needed as a next step.
