### ISSUE TITLE
DataTableColumns - require columns

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#3199]
Figma File

## Problem Statment

How might we visually show required columns within DataTable customization so the 
user can quickly distinguish which ones can and cannot be re-ordered or hidden.

## Summary 

DataTable has the concept of "[managing columns](https://design-system.hpe.design/templates/datatable-customization)." As a user, when managing columns I'd like to be able to:
- Order the columns according to my preference.
- Choose which columns are visible or hidden.

That said, there are some circumstances where a column (or columns) may be required to be visible. This probably occurs most often with the record's primary identifier / name which may be needed to maintain row uniqueness and/or may have navigation associated with it.

During office hours the question was raised "How should required columns be displayed in the managing columns / data table customization context?" 

## ToDos

Your design challenge, should you choose to accept it, is to create a recommendation for "how should required columns be displayed in the managing columns / data table customization context?" In addition, consider the following:

- [x] What are the interactions? Are they interactive?
- [x] Should the user be able to reorder required columns as long as they are visible on the table somewhere?
- [x] How are they styled? 
- [x] How does the user know this particular is required?
- [ ] Can / should multiple columns be required?
- [ ] Others?

## Deliverables

- [x] Recommended interaction design
- [x] Recommended visual design
- [ ] Schedule dedicated share-out for review/discussion/critique
- [x] Incorporate feedback as appropriate and solidify recommendations
- [ ] Create follow on issue for the following as appropriate:
  - [ ] DataTableColumns - (If needed) Create a coded prototype to assist / inform interactive behaviors
  - [ ] DataTableColumns - Update Figma component with required columns
  - [ ] DataTableColumns - Extend Grommet to accommodate required columns

**Comment by vavalos5** [comment]
[Created 2 visual styles](https://www.figma.com/file/TonE8uQ33e5QJRPknZx36q/DataTable-Customization?type=design&node-id=3122%3A14228&t=18URCBSa6i76OYP5-1). This is still WIP but looking to get some initial reactions and feedback before moving forward.

I've also begun annotation keyboard interactions, but would like to talk to a dev on how we handle disabled list items. I feel it is important for them to be read out loud. by a screen reader and let users know that the disabled items are checked but cannot be checked/unchecked or re-ordered as they're mandatory columns. I tried doing some research and kept finding just particularly that disabled items are not focusable. But how can we let a person with vision impairments know these items exist? Perhaps I'll have to connect with Bill when he returns from vacation.

**Comment by vavalos5** [comment]
Will not be ready for demoing on 6/20.

**Comment by halocline** [comment]
> [Created 2 visual styles](https://www.figma.com/file/TonE8uQ33e5QJRPknZx36q/DataTable-Customization?type=design&node-id=3122%3A14228&t=18URCBSa6i76OYP5-1). This is still WIP but looking to get some initial reactions and feedback before moving forward.
>

Good start. I've left a couple comments in Figma, but in general thinking we head in option 1's direction since it is consistent with what is implemented in [SelectMultiple](https://storybook.grommet.io/?path=/story/input-selectmultiple-disabled--disabled&globals=theme:hpe).
 
> I've also begun annotation keyboard interactions, but would like to talk to a dev on how we handle disabled list items. I feel it is important for them to be read out loud. by a screen reader and let users know that the disabled items are checked but cannot be checked/unchecked or re-ordered as they're mandatory columns. I tried doing some research and kept finding just particularly that disabled items are not focusable. But how can we let a person with vision impairments know these items exist? Perhaps I'll have to connect with Bill when he returns from vacation.
> 

SelectMultiple has implemented the desired screen reader experience. We should be mirroring the same screen reader experience here.

**Comment by vavalos5** [comment]
Thanks @halocline I've addressed the small comments and have moved the items [ready to be implemented into the site in the WIP page](https://www.figma.com/file/TonE8uQ33e5QJRPknZx36q/DataTable-Customization?type=design&node-id=3133%3A30996&t=1UREEOlMqW8cEK35-1).

Let me know if we're good to close @halocline

**Comment by vavalos5** [comment]
Follow up ticket: #3408 to add to the design system site.

**Comment by halocline** [comment]
Added https://github.com/grommet/hpe-design-system/issues/3412 as well for the Grommet enhancement.

**Comment by halocline** [comment]
> Thanks @halocline I've addressed the small comments and have moved the items [ready to be implemented into the site in the WIP page](https://www.figma.com/file/TonE8uQ33e5QJRPknZx36q/DataTable-Customization?type=design&node-id=3133%3A30996&t=1UREEOlMqW8cEK35-1).
> 
> Let me know if we're good to close @halocline

Good to close now. Thank you!
