### ISSUE TITLE
Brand Refresh - Divide Figma tickets amongst designers

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#3201]
Creating a follow up ticket on #3175 for us designers to connect and divide creating subsequent tickets based off of the ticket I named above. Then we can decide how we're going to divide and conquer the Figma changes need and when we're going to do it.

**Comment by vavalos5** [comment]
List of changes needed and to be divided amongst designers:

Colors:
- [ ] Changed light mode `text-strong` to `#444444`.
- [ ] Changed light mode `text` to `#6F6F6F`.
- [ ] Changed layer overlay background to `#0000001F`.
- [ ] Changed `selected-background` to `brand`.
- [ ] Changed `selected-text` to `text-primary-button` (white, necessary to meet color contrast on HPE green background).
- [ ] Changed `control` to `brand`.

Accordion:
- [ ] Changed title to use heading `level: 3`.
- [ ] Changed arrow from `FormDown` to `Down`


Anchor:
- [ ] Changed color to `text-strong`.
- [ ] Changed weight to `bold` for large and greater (700).
- [ ] For sizes large and greater, changed color to `brand`.

Button:

- [ ] Increased rounding on all button kinds and sizes from 2em (full rounding). The exception is toolbar buttons which retain the existing 6px radius.
- [ ] For medium buttons, changed padding to `6px` vertical and `18px` horizontal for buttons with labels and to `9px` for icon-only buttons to ensure a `36px` height.
- [ ] For small buttons, changed padding to `6px` vertical and `18px` horizontal for buttons with labels and to `9px` for icon-only buttons to ensure a `36px` height.
- [ ] For large buttons, changed padding to `8px` vertical and `24px` horizontal for buttons with labels and to `15px` for icon-only buttons to ensure a `48px` height.
- [ ] Removed border from toolbar button.
- [ ] Changed hover treatment of primary buttons to use a linear-gradient.
- [ ] Changed disabled treatment of buttons to use `opacity: 0.3`.
- [ ] Reduced size of `badge` to be more proportional with reduced icon sizes.

Calendar:

- [ ] Changed use of Heading to Text for proper semantic rendering of month and year.
- [ ] Changed use of `FormNext` and `FormPrevious` icons to `Next` and `Previous`.
- [ ] Changed selected day to have background `brand` and color `text-primary-button` (white, necessary to meet color contrast requirement on HPE green background).

CheckBox:

- [ ] Changed selected state to use `brand`.

DataTable:

- [ ] Changed heading cell weight to `500`.
- [ ] Changed primary key weight to `400` and color to `text-strong`.
- [ ] Increased pinned cell background blur to `12px`.

Heading:
The following are formatted as `font-size` / `line-height` / `font-weight`.

Level 1:

- [ ] small: 24px / 24px / 500
- [ ] medium: 36px / 36px / 400
- [ ] large: 48px / 48px / 400
- [ ] xlarge: 60px / 60px / 400

Level 2:

- [ ] small: 20px / 20px / 500
- [ ] medium: 24px / 24px / 500
- [ ] large: 36px / 36px / 400
- [ ] xlarge: 48px / 48px / 400

Level 3:

- [ ] small: 16px / 16px / 600
- [ ] medium: 20px / 20px / 500
- [ ] large: 24px / 24px / 500
- [ ] xlarge: 36px / 36px / 500

Level 4:

- [ ] small: 12px / 12px / 600
- [ ] medium: 16px / 16px / 600
- [ ] large: 20px / 20px / 500
- [ ] xlarge: 24px / 24px / 500

Level 5:

- [ ] small: 12px / 12px / 600
- [ ] medium: 12px / 12px / 600
- [ ] large: 16px / 16px / 600
- [ ] xlarge: 20px / 20px / 500

Level 6:

- [ ] small: 12px / 12px / 600
- [ ] medium: 12px / 12px / 600
- [ ] large: 12px / 12px / 600
- [ ] xlarge: 16px / 16px / 600

Icons:

- [ ] Changed sizing to align with font-size values: small (`16px`), medium (`18px`), large (`24px`), xlarge (`30px`), xxlarge (`36px`).
- [ ] Added `disabledScaleDown` which ensures for certain simple icons (Close, LinkNext, etc.) that the stroke does not scale down at smaller sizes which was creating undesirably thin icons.

Layer:

- [ ] Changed layer overlay background color to `#0000001F`.
- [ ] Added `blur(12px)` to overlay.

Menu:

- [ ] Changed arrow from `FormDown` to `Down`

NameValuePair:

- [ ] Changed name color to `text-strong`.
- [ ] Changed name weight to `500`.

Notification:

- [ ] Changed weight to `500` and color to `text-strong`.

PageHeader:

- [ ] Changed subtitle to size `xlarge`.

Paragraph:
The following are formatted as `font-size / line-height / font-weight / max-width`.

- [ ] xsmall: 14px / 16px / 400 / 25em
- [ ] small: 16px / 20px / 400 / 25em
- [ ] medium: 18px / 24px / 400 / 25em
- [ ] large: 24px / 32px / 400 / 25em
- [ ] xlarge: 30px / 36px / 300 / 25em
- [ ] xxlarge: 36px / 40px / 300 / 25em

RadioButton:

- [ ] Changed selected state to use `brand`.

RangeInput:

- [ ] Changed color to `brand`.

RangeSelector:

- [ ] Changed color to `brand`.

Select:

- [ ] Changed selected state to use `brand`.
- [ ] Changed weight of selected option to use `bold` in order to meet color contrast requirement on HPE green background.
- [ ] Changed arrow from `FormDown` to `Down`

Spinner:

- [ ] Changed color to `brand`.

StarRating:
- [ ] Changed color to `brand`.

Tab:

- [ ] Changed color to `text`.
- [ ] Changed weight of active tab to `bold`.
- [ ] Changed border color of active tab to `brand`.
- [ ] Reduced border size of active tab to `medium` (4px).
- [ ] Added border color of `border-weak` on hover.
- [ ] Changed horizontal pad of tab to `18px` to align with Button.

Tabs:

- [ ] Added `alignSelf: “start”` to ensure bottom border under all tab controls is only under the tabs rather than extending across entire container.
- [ ] Reduced border size under all tab controls to `xsmall`.
- [ ] Changed border color under all tab controls to `border-weak`.

Table:

- [ ] Changed footer font-weight to `500`.

Tag:

- [ ] Changed value font-weight to `500`.

Text:
The following are formatted as `font-size / line-height / font-weight`.

- [ ] xsmall: 14px / 16px / 400
- [ ] small: 16px / 20px / 400
- [ ] medium: 18px / 24px / 400 (not changed)
- [ ] large: 24px / 32px / 400
- [ ] xlarge: 30px / 36px / 300
- [ ] xxlarge: 36px / 40px / 300
- [ ] 3xl: 42px / 46px / 300
- [ ] 4xl: 48px / 48px / 300
- [ ] 5xl: 72px / 72px / 300
- [ ] 6xl: 72px / 72px / 300

ThumbsRating:
- [ ] Changed color to `brand`

**Comment by vavalos5** [comment]
Another ticket to consider: #2940

**Comment by vavalos5** [comment]
We've chatted with Ashley and Joelle who will be replicating our Typography and Color style sheets and apply our new color changes within a new Figma environment we've started. The environment is private to other HPE employees right now so they don't access it at the moment.

Tomorrow: 
We have a meeting set up to discuss testing out components and service's Figma files. We will be going through a few together with Ashley and Joelle and let them finish the rest.

Monday:
Connect with a dev to ensure the colors and text styles are aligned to the theme before pushing anything.

**Comment by vavalos5** [comment]
Icons- we might have to look to see if there's a plug in to meet all of the different sizes we have available in Grommet. If not, we're leaving this one out for now because it's going to be a lot of heavy work for us.

**Comment by taysea** [comment]
> however, in the theme, I noticed that sizes small and medium, the text weight looks like it's using `500` or `600`. Can you confirm please. Also, it looks like we no longer have size xsmall. Is that correct?
> 

`xsmall` is still supported as a size. It mirrors the styling of `small` and `medium` except for that is uses the `xsmall` text size.

> Some of the anchors have an arrow, is there guidance on when that should be used?

I don't have guidance from Chris of when to use that arrow, can clarify with once he's back in office. However, when it is used it should use the `brand` green.

> I also noticed that we only have sizes `small,` `medium` and `large` for anchors now. Want to confirm.
> 

All the anchor sizes previously supported are still supported. `medium` and smaller should use the `text-strong` treatment, `large` and bigger should use the `brand` color treatment. The anchor text size aligns with the font-size at that t-shirt size.

> Thanks!

**Comment by vavalos5** [comment]
Documenting a question that came to mind as i'm changing text styles: 
Should anchor be a component now that it has an icon rather than a text style?

**Comment by taysea** [comment]
> Documenting a question that came to mind as i'm changing text styles: Should anchor be a component now that it has an icon rather than a text style?

Isn't Anchor already a component?

**Comment by vavalos5** [comment]
> > Documenting a question that came to mind as i'm changing text styles: Should anchor be a component now that it has an icon rather than a text style?
> 
> Isn't Anchor already a component?

It is but we don't have it offered in different t-shirt sizes and now we will have to add a variant with an arrow.

**Comment by vavalos5** [comment]
Confirming text-xweak for light and dark mode are no longer colors in the theme @taysea

**Comment by taysea** [comment]
> Confirming text-xweak for light and dark mode are no longer colors in the theme @taysea

Those colors are still needed, it is used for `disabled` text states. They are not changed.

**Comment by vavalos5** [comment]
Asking @taysea and @KennyAtHPE to review the [typography styles in Figma](https://www.figma.com/file/oJhw3JqMemtbwWjlLPWW5O/HPE-Typography-Styles?node-id=0%3A1&t=wuq6LipiM5FZPbXo-1) and the [color changes in Figma](https://www.figma.com/file/eZYR3dtWdb9U90QvJ7p3T9/HPE-Color-Styles?node-id=590%3A981&t=H9UGLBZoAXpmdT6l-1) please. :) 

Please note that I haven't created new typography styles, so you'll see them as broken at the moment to easily see the text sizes. Once confirmed that they're aligned, I will make them into new text styles.

For colors, I have changed default text and text-strong in light mode as mentioned above. I did change the swatch color on the right panel but haven't pushed change. Once confirmed, I'll push the new color styles which will then help me update the typography styles since they're still using our old text-strong color. I left it like that so when I push colors, I can commit the changes much easily from my end.

**Comment by KennyAtHPE** [comment]
Couple of clarification questions @taysea:

**Buttons**
- "Increased rounding on all button kinds and sizes from 2em (full rounding)." What are we changing the rounding value too specifically?
- For icon-only buttons, are we only changing the horizontal padding? (Small and Medium to 9px, Large to 15px)?
- Do the button changes also apply to the CTA-variants?
<img width="612" alt="Screen Shot 2023-03-22 at 7 26 05 AM" src="https://user-images.githubusercontent.com/86075038/226935278-59699e35-9ba7-442c-89c8-a9cc34a01f52.png">
Ex. Small, medium, and large buttons. Left side is what we have now and the right side is with the proposed padding changes.
- I just want to confirm this addition to the horizontal padding is what we want. Personally speaking, it seems a bit wide to me, especially for the small variant.

**Calendar**
<img width="553" alt="Screen Shot 2023-03-22 at 6 57 35 AM" src="https://user-images.githubusercontent.com/86075038/226927152-36bdb07a-6e0f-4e43-80c3-a2cc1c6595cf.png">
- "Changed selected day to have background brand and color text-primary-button (white, necessary to meet color contrast requirement on HPE green background)." Does text-primary-button equal Dark/Text? Any color changes to the 19th day?

**Menu**
<img width="1025" alt="Screen Shot 2023-03-22 at 7 03 40 AM" src="https://user-images.githubusercontent.com/86075038/226928813-48a9d11e-9aa1-4a78-ad74-00d10a9a485c.png">
- Down is being used on the left and Form/Down is being used on the right. Just wanting to confirm we want to make this change since it doesn't look proportional to me.

**Select**
<img width="790" alt="Screen Shot 2023-03-22 at 7 37 12 AM" src="https://user-images.githubusercontent.com/86075038/226938477-150e771f-2afc-4f06-a4b9-ef7cfdf92094.png">
- Same question as above

@vavalos5 Do you know what the 500-weight text style is within our Assets?

**Comment by KennyAtHPE** [comment]
Things I've noticed along the way:
- Text within some components are not linked with our text styles. All text should be linked so that they can pull in any future text-related updates
     - Menu, Buttons, possibly more 
- I omitted a majority of changes to the Tabs component since it currently has a lot of issues. We need to retake a look at this component altogether to complete the brand refresh changes.

**Comment by vavalos5** [comment]
Kenny, for the button question, this is something we're going to have figure out on our end in Figma. Though, I'm not sure if Chris has this somewhere in his Figma files. We can look through them and see if we can find what the rounding is. The rounding in code seems to be different from that in Figma.

For your question in regards to the 500 weight. 500 = medium text size. Lmk if you have more Qs on that.

**Comment by KennyAtHPE** [comment]
@taysea couple of more clarifying questions:

**Button**
- For Large icon-only buttons, is the padding supposed to be 12px all around instead of 15px? 15px makes the button's 54px instead of 48px
- What should the icon size be for XL buttons?
- What is the padding for XL icon-only buttons?
![image](https://user-images.githubusercontent.com/86075038/227573267-2ede5518-eb8b-4401-85dd-3b5bb713391a.png)
- Our disabled states currently look like this, but should they be styled differently?

**Notifications**
- Is the weight change only for the Title and not the message?

**Menu**
- Are we styling this similarly to Medium buttons? Same padding, font size, icon size, rounding, etc.?

**Tag**
- Should value-only tags have font-weight 500 also?

**Comment by KennyAtHPE** [comment]
Asking @vavalos5 for a review of all the components I worked on minus Buttons and Select, still ironing out some details on those two.

**Comment by taysea** [comment]
> @taysea couple of more clarifying questions:
> 
> **Button**
> 
> * For Large icon-only buttons, is the padding supposed to be 12px all around instead of 15px? 15px makes the button's 54px instead of 48px

Yes, [12px](https://github.com/grommet/grommet-theme-hpe/blob/master/src/js/themes/hpe.js#L501).

> * What should the icon size be for XL buttons?

The icon-sizing aligns with the font-size for all button sizes. So "xlarge" is 30x30.

> * What is the padding for XL icon-only buttons?

[21px](https://github.com/grommet/grommet-theme-hpe/blob/master/src/js/themes/hpe.js#L501).

>   ![image](https://user-images.githubusercontent.com/86075038/227573267-2ede5518-eb8b-4401-85dd-3b5bb713391a.png)
> * Our disabled states currently look like this, but should they be styled differently?

The disabled state now has no changes to the border/background/label color. Instead, opacity 30% is applied to the entire button.
> 
> **Notifications**
> 
> * Is the weight change only for the Title and not the message?

Correct.

> 
> **Menu**
> 
> * Are we styling this similarly to Medium buttons? Same padding, font size, icon size, rounding, etc.?
> 
Yes. In Grommet, Menu is built with a "default" button.

> **Tag**
> 
> * Should value-only tags have font-weight 500 also?

Yes, the [value weight is 500](https://github.com/grommet/grommet-theme-hpe/blob/master/src/js/themes/hpe.js#L1534).

**Comment by vavalos5** [comment]
All changes have been applied to Figma with the exception on Select, Tabs and Interactive Tabs, icons and gradients due to  Figma issues, refactoring needed and don't have them available as tokens.

Kenny and I have reviewed each other's changes, made adjustments and completed.

#3239 is the next step to publish changes
