### ISSUE TITLE
Page Templates - Modals

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#3204]
Figma file - TBD

## Problem Statement

How might we provide easy to use modal page templates  to our designers and developer so that they can copy and paste them when designing?

## Acceptance Criteria

- [ ] publish Detail modal page templates in a format consistent with the [home page template]()

## Tasks

- [ ]  create success criteria
- [ ]  collect and review modal page templates examples and understand what it entails [1 day max]
- [ ]  gather modal page templates examples from other teams like Storage and Compute [2 days max]
- [ ]  V1 - ideate ideas on how to visually layout modal page templates (skeletal to more detailed view ((examples)) [2 days max]
- [ ]  connect w/ Team
- [ ]  share + gather feedback from Scott + Eric
- [ ]  implement feedback
- [ ]  share + gather feedback from stakeholders
- [ ]  implement feedback

**Stakeholders**:
Chris
Gina
Justin
Amanda
