### ISSUE TITLE
Brand Refresh - strategy for partner Figma consumption

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#3217]
## Tasks

- [x] schedule a meeting to discuss, involve any helpful stakeholders, like Greg
- [x] determine how we want to roll out the component updates
- [x] meet with key stakeholders 1-1 to discuss, Justin, Gina, ???
- [x] determine how we want to handle the migration guide for designers, probably a Figma file, easier for designers to consume, perhaps a recording as well

**Comment by vavalos5** [comment]
Done and detailed view in ticket #3220
