### ISSUE TITLE
ButtonGroup - Figma layout template (i.e. slot component which controls the horizontal gap of its children elements)

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#3292]
Parent Issue: https://github.com/grommet/hpe-design-system/issues/3291

Create a Figma layout template (i.e. slot component which controls the horizontal gap of its children elements) which can be used to display a collection of buttons, menus, search input, etc.

**Pre-tasks**:
- [x] Review the [parent issue](https://github.com/grommet/hpe-design-system/issues/3291) for context.
- [x] Review this document:
[Action Button Rows.pdf](https://github.com/grommet/hpe-design-system/files/11237610/Action.Button.Rows.-.User.Experience.-.Nimble.Confluence.pdf)

**Acceptance criteria**:
- [x] Should present children horizontally with a gap between each child
- [x] Should not be opinionated about what types of children it accepts. Should be able to accept many types of children (e.g. buttons, menus, icon only buttons, inputs such as search).
- [ ] Should show and hide children as room allows. If there is not enough room for all children, the children would be placed in an overflow menu. Not sure how this might be implemented in the Figma component, but in the file there should be demonstrations of what happens when there is not enough room for all components.
- [ ] Should have an overflow menu, which when opened presents the children as menu options.
- [x] Should be able to placed in a variety of other layout scenarios such as Toolbar, PageHeader, Layer, Rich Text editor, etc.
- [ ] Should consider a divider (whether visual element or greater spacing) which could be used to group like controls.

**Comment by Keeth-HPe** [comment]
@halocline  @L0ZZI 

Here are some questions I had while I was exploring on the button rows. Please correct me if I'm wrong. Thank you!

1. I'd suggest to have components with variants, where users can swap the button to menus, icon only buttons or change to a variant that has search input, instead of slot component.
  Reason:  
 For slot component we need to Pre-define slots to ensure that the content within the slot maintains a consistent layout and position. By defining the slot dimensions and properties in advance, we can ensure that the content being swapped in will fit within the designated area and not disrupt the design.
 But on our case, its not practical to define all input components anticipating future possibilities

  
2. We can hide and show children, but according to my research:  We should not add more than 3 buttons in a button row: When we provide too many options, users end up doing nothing.  When designing, we should think about the most important actions we want your users to take. 

3. Not sure where we would require a divider, please can I get more context here..

https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/branch/MCgMTr2jnIehY0yuD3DCX3/HPE-Design-System-Components?node-id=9323%3A107287&t=qsIWSwXJ3VLFVZZZ-1

**Comment by halocline** [comment]
> 1. I'd suggest to have components with variants, where users can swap the button to menus, icon only buttons or change to a variant that has search input, instead of slot component.
>    Reason:
>    For slot component we need to Pre-define slots to ensure that the content within the slot maintains a consistent layout and position. By defining the slot dimensions and properties in advance, we can ensure that the content being swapped in will fit within the designated area and not disrupt the design.
>    But on our case, its not practical to define all input components anticipating future possibilities

I agree that that "its not practical to define all ... possibilities." Because of that, I don't know that we can even predict the number of slots to include.

**Phase 1** - For the first pass, I am hoping we can begin with a really basic component which does the following:
- Provides row oriented direction
- Default spacing of 'small' (12px)
- No padding
- Will grow with its content (i.e. we can't prehugs its content vertically and horizontally)
- Ability to justify left or right

I don't know if that is a component with a single slot which has auto-layout, or if it is just a component with auto-layout. I'm not familiar enough, yet, with the details of Figma implementation to know, but the key is flexibility.

**Phase 2** - We can add in options for:
- Overflow menu
- Gap spacing property/variant where default spacing is 12px, but we may want to accommodate nested button groups, where spacing between each group is default, but we'd want tighter spacing (e.g. 6px) within each child group.

Let's not execute on phase 2 right now.

> 2. We can hide and show children, but according to my research: We should not add more than 3 buttons in a button row: When we provide too many options, users end up doing nothing.  When designing, we should think about the most important actions we want your users to take.

I think this is good guidance, however from a component functionality standpoint, I would like to err on providing flexibility and not restrict the number of children at this time. 

For example, perhaps I want to implement a rich-text editor with a variety of controls. I'd want to make use of the Button Group and would not want to be limited to only three children.

![Screenshot 2023-04-24 at 11 37 40 AM](https://user-images.githubusercontent.com/1756948/234077872-f97ad549-8b88-4ea0-a78b-2304bef6f3ac.png)

**Comment by Keeth-HPe** [comment]
@halocline 
Provides row oriented direction✅
Default spacing of 'small' (12px) ✅
No padding✅

We can implement the above points but its not possible to make the instance grow. 
❌Will grow with its content (i.e. we can't predict the content, so don't want a fixed size, instead hugs its content vertically and horizontally)❌

**Reason** :
Only master components can be edited. Instances only allow overriding properties, such as colors, opacity, visibility, stroke width, autolayout constraints, border radius and text content. You can't move things around within an instance, or add/remove content.

So if a designer has to use this component (built this way), they have to access the source file and copy paste the "master" component into their working file to edit over it.  User cannot access the master component from assets after publishing the component. You will only get instances of the master component.

It is not possible to work on the instance of the master component. Figma technically does not allow that. 

@SOjaHPE

**Comment by halocline** [comment]
@Keeth-HPe , thank you for the detail and explanation. I will have a look later today.

**Comment by KennyAtHPE** [comment]
5/2 update:

Link to the [Figma file](https://www.figma.com/file/Yd9l856KwxjS43zxQSilzE/ControlGroup-%233292?node-id=0%3A1&t=Dxt7pDpiHjJz5JBQ-1) I shared out today

Conclusion from exploration:
- Due to Figma's limitation, creating a ButtonGroup slot component right now isn't worth the effort or time. It would require a lot of effort for us to manage and for us to educate users on how to use it.
- Instead, we can provide pre-defined templates similar to what we do with the layer component. There would not be a variant for a fully customizable ControlGroup

Closing ticket.
