### ISSUE TITLE
Design Tokens - Figma exploration

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#3309]
Research SPIKE --- Proof of concept demoing Figma consuming design tokens from the design tokens repo.

**ToDos**
- [x] Work with @taysea to properly scope this issue
- [x] Check-in with Joelle, whom I believe may have already done some of the plugin research and proof of concept
- [x] Explore the new Figma variables features
- [x] Explore Figma's [Rest API](https://github.com/grommet/hpe-design-tokens/blob/main/global.json): Note in comment below, but we are currently "Organization", and Rest API is only available in enterprise plan which we might be switching to when plan renews
- [x] Explore Figma Design Token related plugins
~~- [ ] Present findings (pros vs cons), demo out a proof of concept, and make suggestions on which to use moving forward~~
- [x] Setup a dedicated session for an official share out

---------------------------
**Background which may be out of date**

- [x] Further exploration about Figma Tokens Studio and its viability for use in managing component styles in Figma
~~- [ ] Add build step in hpe-design-tokens to generate file that's compatible with desired Tokens Studio format.~~
~~- [ ] Demo use of tokens from Github in Figma~~

Current Questions:
- Can our team manage the styles via Figma plugin without all other users needing to install and run the plugin? (It seems like it would be preferred that other users don't rely on a plugin)
- Can Tokens Studio styles be integrated cleanly with Figma native styles?
- Do we want to be relying on a plugin? Is it well maintained?
- There is a steep price ($16/month per user) for the paid features of this plugin -- if we need those features then this plugin is too expensive to support. Need to investigate

---------------------------------

Relevant Links

- [Guide to Figma Variables](https://help.figma.com/hc/en-us/articles/15339657135383-Guide-to-variables-in-Figma)
- [Grommet Global Tokens](https://github.com/grommet/hpe-design-tokens/blob/main/global.json)

**Comment by KennyAtHPE** [comment]
Related #2777

**Comment by KennyAtHPE** [comment]
6/22 update:

Connected with Taylor and showed off some of the new upcoming Figma 'Design Token' features. Will be changing the scope of this ticket to focus more on exploring that as opposed to the plugins.

**Comment by KennyAtHPE** [comment]
6/26 update:

Connected with Joelle and Ashley on their past Token research. They [researched many different plugins](https://www.figma.com/file/C07uBi4kflDIVSODPQfjIq/Design-Tokens?type=design&node-id=1960%3A6821&mode=design&t=sLUw4beLtW6K27Pi-1) and recommended that the DS team should focus on exploring the new Figma features instead. Some concerns they had about utilizing plugins are:
- Pricing
- Instability on whether or not the plugins will be updated in the future
- Figma has been licensing and working with 3rd party token related plugins, so the amount of features should continue to grow within Figma

They also mentioned that the new Figma features:
- Will be free for the next 5 months for beta testing before being locked behind a paywall
- New features are coming out

**Comment by taysea** [comment]
Re: Rest API, getting some errors from Figma's docs so still troubleshooting there.

![Image](https://github.com/grommet/hpe-design-system/assets/12522275/4cb45ab2-a3eb-45ef-8527-35ec2b935423)

**Comment by KennyAtHPE** [comment]
Taylor, Joelle, Ashley, and I have extensively explored the new Figma Variables feature and had a share out with the team. The follow on [ticket](https://github.com/grommet/hpe-design-system/issues/3466) and next steps are to fully set up our Figma Variables within the DS Figma library. These variables should be 1:1 to the tokens we currently have established.

Closing out ticket.
