### ISSUE TITLE
Grommet responsibilities - Explore and define "problem space"

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#3315]
**ToDos**
- [x] Recommendation: Find a partner to collaborate with to select a [Luma recipe](https://www.luma-institute.com/about-luma/luma-system-explore-methods/) or similar to facilitate a design thinking session or two. Appoint a facilitator. Appoint a note-taker / helper.
- [x] Schedule and conduct a design thinking exercise(s) which:
  - Explore and empathize Grommet ecosystem activities, responsibilities, desires, pain points, etc.
  - Defines the problem space(s)

**Acceptance criteria**
- [ ] Problem statement(s) articulated and defined (e.g. "How might we _____ in manner that ______ ...?" or[ MadLibs style](https://slides.grommet.io/?name=Design%20Thinking%20-%20Articulating%20a%20Problem%20Statement#6))
- [ ] Follow on issue created for "Grommet responsibilities - Ideate and prototype the 'solution space'"

**Proposed budget**
- ~ 2 hours prep
- ~ 1-1.5 hours exercise
- ~ 30 min summarizing key outputs

**Comment by jcfilben** [comment]
Update 5/5: making progress but won't get done by the end of this sprint.
Amanda has agreed to facilitate this meeting. She and I discussed ideas and she is working on setting up a FigJam board for us. We have the design thinking exercise scheduled for 5/11.

**Comment by jcfilben** [comment]
Closing, this work is no longer planned
