### ISSUE TITLE
Map - Create design direction and recommendation for map elements and controls

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#3349]
[Figma File](https://www.figma.com/file/bMVkdgHkimCENGHiKPGcYH/Maps?type=design&node-id=1%3A23&t=CfhyysoAVA52JxU8-1)

## Problem Statement
How might we provide users a map so they can zoom in and out, search, filter, view clusters of locations, view server statuses, and drill into content confidently so they can quickly find and drill into locations and servers.

## Summary/Background 

Parent issue https://github.com/grommet/hpe-design-system/issues/3143

**Initial thoughts & recommendations:**
- This is recommended as an issue which team members should swarm and collaborate to explore, define, and ideate.
- Think of map as just another visualization to present a data collection. Like rows in a data table, items in a list, or cards in a grid a map is another means to present a collection of objects which happen to have an associated latitude and longitude. Functionally, the map should be able to present the individual objects, allow a user to browse them, inspect, navigate to detail. The map may likely be accompanied by a data Toolbar with similar search, filters, saved views, etc.
- A user should have choice over their preferred visualization and be able to replace a map with a table, grid, list, etc.

## Todos
- [x] Review history, notes, and use cases collected so far in https://github.com/grommet/hpe-design-system/issues/3143
- [x] Collect Use Cases within Figma
- [x] Collect other Map examples, interact with them
- [x] Pick 2-4 maps, Vicky and Kurt to share with one another
- [x] Define the minimal functionality needed for a MVP map (e.g. display, select, view preview details, navigate to detail, zoom, reset, pan, etc.)
- [x] Create Anatomy
- [x] Define what visual map elements are needed
  - [x] Marker - Vicky
  - [x] Cluster markers - Vicky
  - [x] Status indicators - Vicky
  - [x] Counts - Vicky
  - [x] Popover container - Vicky
  - [x] Map controls and placements (zoom in/out, filter, search, reset) - Kurt
- [x] Create visual explorations for the needed map elements
  - [x] Marker - Vicky
  - [x] Cluster markers - Vicky
  - [x] Status indicators - Vicky
  - [x] Counts - Vicky
  - [x] Popover container - Vicky
  - [x] Map controls and placements (zoom in/out, filter, search, reset) - Kurt
- [x] Share our explorations and recommendations

**Comment by vavalos5** [comment]
I've already created a Figma file where i've included:

- all of the use cases
- notes from our meeting w/ stakeholders
- questions
- roadmap
- a section to collect examples of other maps

For the remainder of the day, Kurt and I will be separately doing our own research and the following:

- explore other examples
- collect those screen shots
- tomorrow come prepared with 3-5 visualizations/maps we thought were best for representing the data we’re looking to represent based on the use cases/needs discussed within the meeting
- I’ll set up a call for tomorrow to discuss

**Comment by vavalos5** [comment]
For tomorrow, i'd like us to have a good understanding of the needs
- Distribute responsibilities amongst one another and continue to do further research on behaviors and interactions
- Explore and ideate ideas

**Comment by vavalos5** [comment]
Storage Figma link to Zoom In/Out pattern: https://www.figma.com/file/6obCqAKgV9BqkjyGu9QOg5/SC_Zoom_In_Out?type=design&node-id=0-1&t=uZDOH3u5hsrMDM1f-0

**Comment by vavalos5** [comment]
Ready for a review to just get some quick reactions and to get thoughts on direction on the [marker and tip styling and behaviors](https://www.figma.com/file/bMVkdgHkimCENGHiKPGcYH/Maps?type=design&node-id=30%3A176&t=DHAlIza5vvvlUDAi-1). @ericsoderberghp @halocline @SOjaHPE

**Comment by vavalos5** [comment]
Ready for second set of eyes @halocline on new explorations. Including thoughts on the [tip](https://www.figma.com/file/bMVkdgHkimCENGHiKPGcYH/Maps?type=design&node-id=30%3A280&t=1C4Kf7fga29jzFJC-1)

**Comment by vavalos5** [comment]
Had a call with Kurt to walk him through few initial visual explorations he can continue to explore for the zoom in/out and reset buttons. 

From that, he will continue to primarily focus on creating a few different visual stylings for those buttons and applying them to a map to better help the visual storyline of the styling and placement. Will be checking those explorations tomorrow.

I've set up a call w/ Joelle for tomorrow to discuss research she and others have conducted in regards to status/state within data viz to extract some information from there and apply to the badging i'm doing on the markers and clusters.

**Comment by SOjaHPE** [comment]
[like]  Oja, Scott reacted to your message:
________________________________

**Comment by halocline** [comment]
> The following might be over scope, but I was doing some research on best practices on how to cluster many markers and how many there should be within a certain range. It turns out this is defined in the API. Something i'm not familiar with. I don't think we need to necessarily define how many clusters or markers we want to have near one another but rather I think this is defined in the API. Thoughts..? I've gathered research on this [here where it takes me to algorithms](https://www.figma.com/file/bMVkdgHkimCENGHiKPGcYH/Maps?type=design&node-id=30%3A526&t=Vds3k76xSKEHL905-1).

Yes, there are well established approaches to maps, density, and clustering so we plan to build off existing standards and technologies.

"I don't think we need to necessarily define how many clusters or markers we want to have near one another but rather I think this is defined in the API. Thoughts..?" --> Yes!!! This is why the original issue attempted to be focused on the visual design direction. When the map tech we choose tells us to cluster, we will display our cluster maker. When it says show individual location, we will do its bidding ;)

**Comment by halocline** [comment]
> From that, he will continue to primarily focus on creating a few different visual stylings for those buttons and applying them to a map to better help the visual storyline of the styling and placement. Will be checking those explorations tomorrow.
> 

Hopefully the styling of the buttons aligns closely to our existing styles. I am interested to see the placed in context on the map.
- Do they have visual affordance? Are they recognizable?
- In which quadrant of the map should they be placed?
- What are the minimum number of controls we can get away with? Which controls are they?

**Comment by halocline** [comment]
Good notes, by the way. Thank you!

**Comment by vavalos5** [comment]
Just got off the phone with Joelle - she's not working on identifying status colors as of right now but rather just primarily graph colors, how they'll look at a larger and smaller scale as well as combinations. I'll work on gathering some research in regards to status on badges.

I also connected with Kurt and he's really close to needing a review.

**Comment by SOjaHPE** [comment]
[like]  Oja, Scott reacted to your message:
________________________________

**Comment by vavalos5** [comment]
@halocline Kurt's Zoom in/out and reset control explorations are ready to be [reviewed here(https://www.figma.com/file/bMVkdgHkimCENGHiKPGcYH/Maps?type=design&node-id=191%3A57079&t=kSQKaPNF7bCx2gUR-1)

**Comment by vavalos5** [comment]
@halocline Clusters and Markers are ready for a review [here](https://www.figma.com/file/bMVkdgHkimCENGHiKPGcYH/Maps?type=design&node-id=237%3A57790&t=AIMDfbrxNYQGPssO-1).

**Comment by kurt-ph** [comment]
@halocline Presentation board we reviewed today in our sprint demo [here](https://www.figma.com/file/bMVkdgHkimCENGHiKPGcYH/Maps?type=design&node-id=370%3A75773&t=wiE5sQ9T17G5LyWc-1).

**Comment by halocline** [comment]
Thank you, @kurt-ph. Thank you, @vavalos5. Nice work. We've got what we need to move on to next steps.
