### ISSUE TITLE
Map - Decide on whether we are shipping a importable component or a pattern implementors may reference

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#3384]
## Suggestion

As a dev team, 

## For consideration

- [x] Where should Map live?
- Map and related components will live in a separate repository from grommet

- [x] What is the contract HPE Design System is committing to?

- Committing to maintenance + support of an additional project which will be relied on by HPE teams
- Committing to fixes/enhancements/dependency upgrades/releases/etc.

- Keeping separate from grommet allows us to focus on the use cases from HPE
- Will allow lower maintenance vs trying to commit to and support mapping requests from the open-source community
- Keeps what we are shipping in grommet focused to base components -- limits additional dependencies/bundle size/etc and stays true to grommet's focus/strengths
- Will allow flexibility in the future to shift to other technologies if needed/desired

- [x] What does the developer experience consuming Map look like?
- Implementation is fairly intuitive with passing children, using marker cluster

- To be revisited from implementation-side: The box rounding is built into the marker pin. Is there a way to be more flexible to allow different shapes? Applies to maintenance as well
- To be revisited from design-side: Adding extra text to individual marker, visually big
- To be discussed once we review our use case implementations

- [x] What is the API like?
- Goal is to stick as closely to leaflet API as possible
- To discuss later: Need to assess areas where that is limiting/come up with shared understanding of when to extend props vs have the caller implement on their own (to consider is consistency across teams, eliminating one-offs)
- To discuss later: How much to rely on leaflet functionality vs react-leaflet?

- [x] Is the HPE Design System staffed to support and commit to long term support? 
- With the goal to keep the API as aligned with leaflet as possible/minimizing the complexity of props we extend/etc., it should be fairly stable to maintain. Primarily focused on keeping up to date on dependencies, etc.
- There are some unknowns with how teams will consume/where they will want to extend or take map features.

- [x] What are contingency options should the team not have staffing to support?
- Leaflet is open-source and allows wide flexibility in the implementation. Callers should be able to implement their designs flexibly using Leaflet's API.

## Map capabilities to consider in assessment

(may be revised to MVP-appropriate level)

**Plot locations - (Jessica)**
- [x] Receive array of longitude-latitude coordinates and plot locations on map, displayed as individual location markers
- [x] Receive locations as a GeoJSON object and plot individual locations on map.

PR: https://github.com/grommet/grommet-leaflet/pull/5

**Individual locations** (Taylor)
- [x] Display an individual location as a custom Grommet-based marker.
- [x] Individual Grommet-based markers should be able to be customized based on status (good, warning, critical).

PR: https://github.com/grommet/grommet-leaflet/pull/6

**Location clusters** (Taylor)
- [x] Consolidate a group of locations and display as a custom Grommet-based "cluster marker."
- [x] Grommet-based "cluster markers" should be able to be customized based on status (good, warning, critical).
- [x] Grommet-based "cluster markers" should be able to display the number of individual locations contained in the cluster.
- [x] Grommet-based "cluster markers" should be able to display a custom label in place number of locations.
- [ ] Grommet-based "cluster markers" should be able to display custom children.

PR: https://github.com/grommet/grommet-leaflet/pull/7

**Zoom - (Jessica)**
- [x] Display styled (+/-) zoom controls
- [x] Display reset / "fit my data" zoom control
- [x] Initialize zoom level at "fit my data" level

https://github.com/grommet/grommet-leaflet/pull/9

**Reveal additional location detail** (Taylor)
- [x] Markers (and Cluster Markers) should be able to reveal a "pop up" which can display any custom Grommet children.
- [x] Allow interactive element such as an anchor allowing for navigation to an object's detail page or filtered data view. (Revisit with designers. It seems the intent is so have this appear on hover and therefor not include interactive elements in it)

PR: https://github.com/grommet/grommet-leaflet/pull/10

**Others**
- [ ] List others as considered
- [ ] Add Google Maps assessment to mapping options comparison, add security considerations as a line item: https://www.figma.com/file/5wrkWT2NllOoInCWVHU4KY/Mapping-Options?type=whiteboard&node-id=0-1&t=sg1tbyOFxhOfKj4m-0

##Deliverables
- [x] #3393 [time-boxed to 1 week, due at Show & Tell]
- [x] #3394 [time-boxed to 1 week, due at Show & Tell]
- [x] Recommendation on pattern vs. component.
- [ ] Draft API surface.
- [x] #3385
- [ ] https://github.com/grommet/grommet-leaflet/issues/24
- [ ] Assess scope, provide level of confidence delivering (need to discuss this more, likely after completing https://github.com/grommet/grommet-leaflet/issues/24)
