### ISSUE TITLE
Charting - Create a decision tree / framework to fit use case to optimal data visualization.

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#3390]
Tracked by #3389 

## ToDos

There are well established best practices for which data visualizations best support particular types of analysis, including a few decision tree frameworks established by academics specializing in data visualization -- HPE Design System should leverage these experts' work.

- [x] Research / collect available data visualization decision frameworks (I have seen one presented as kind of 4 quadrants where the center is a starting point and the reader answers a few yes/no type questions and is guided to the right viz for their need).
- [x] Curate shortlist of most useful.

## Deliverable

- [x] Prototype of decision tree or framework which guides a designer from their use case (analytical question) to optimal visualization.

**Comment by vavalos5** [comment]
Assuming we're trying to do something similar to this image below.
![Image](https://github.com/grommet/hpe-design-system/assets/62117454/a5741ca9-fd81-4085-8f83-693ada8bdc75)

For whoever is working on this, here's a previous [file](https://www.figma.com/file/HuUVMlbOx6Nrc9EgFCkHrY/Data-Visualization?type=design&node-id=64%3A0&t=IlaC7toWsdR9J9X3-1) we've worked out of before.

**Comment by kurt-ph** [comment]
Here is a short curated list of the most useful & relevent according to my research findings & case studies on data visualizations:

Bar Charts: 

- Group Bar Charts 
- Cluster Bar Charts
- Histogram Bar Charts
- Stacked Bar Charts

Line Charts: 

- Basic Line Chart
- Smooth Line Chart
- Step Line Chart
- Area Chart
- Range Line Chart
- Multi-Line Chart
- Sparkline

Pie Charts: 

- Basic Pie Chart
- Donut Chart
- Exploded Pie Chart
- Multi-level Pie Chart
- Nested Pie Chart
- Variable Width Pie Chart

Scatter Plots: 

- Basic Scatter Chart
- Bubble Chart
- Grouped Scatter Chart
- Heatmap Scatter Chart
- Contour Scatter Chart
- 3D Scatter Chart
- Polar Scatter Chart

Area Charts: 

- Basic Area Chart
- Stacked Area Chart
- Range Area Chart
- Polar Area Chart

Heatmaps: 

- Basic Heatmap Chart
- Correlation Heatmap Chart
- Geographic Heatmap Chart
- Hierarchical Heatmap Chart

Treemaps: 

- Basic Treemap
- Squarified Treemap
- Slice-and-Dice Treemap
- Strip Treemap
- Circular Treemap

Gauge Charts: 

- Basic Gauge Chart
- Dial Gauge Chart
- Thermometer Gauge Chart
- Angular Gauge Chart
- Semi-Circular Gauge Chart

Network Diagrams: 

- Node-Link Diagram
- Force-Directed Graph
- Sankey Diagram
- Chord Diagram
- Radial Tree Diagram

Sankey Diagrams: 

- Basic Sankey Diagram
- Multi-Level Sankey Diagram
- Circular Sankey Diagram
- Horizontal Sankey Diagram
- Vertical Sankey Diagram

Sunburst Chart:

- Basic Sunburst Chart
- Hierarchical Sunburst Chart
- Radial Sunburst Chart
- Multi-level Sunburst Chart
- Nested Sunburst Chart

**Comment by kurt-ph** [comment]
Updates for Charting: 

- Explored and analyzed existing data visualization decision tree frameworks developed by academics and experts to understand the best practices and guidelines for selecting appropriate charts.
- Conducted a comparative analysis of various data visualization techniques, considering factors such as data complexity, message clarity, audience engagement, and visual effectiveness.
- Researched and gathered insights on the latest trends and emerging techniques in data visualization, ensuring that the recommendations for the HPE Design System are up-to-date and aligned with industry standards.
- Research data visualizations in general and its best practices on how to use as well as general use case.
- Made a list of some recommendations of data charts that would be useful according to my research & findings.
- In progress of developing decision tree in order to summarize data viz decision that points and guide designers to the most appropriate data visualization chart. Goal would be summarized flow of best general use.

**Comment by kurt-ph** [comment]
Here is the Charting on the decision tree so far: I've included the 4 different quadrants.
https://www.figma.com/file/HuUVMlbOx6Nrc9EgFCkHrY/Data-Visualization?type=design&node-id=1%3A6&t=vEiD7VZlv36Cqa2H-1

**Comment by kurt-ph** [comment]
@halocline @SeamusLeonardHPE
In Review: Any feedback would be helpful, sharing with other designers for feedback
https://www.figma.com/file/HuUVMlbOx6Nrc9EgFCkHrY/Data-Visualization?type=design&node-id=1%3A6&t=XIQ4qJLP40TRU58M-1

**Comment by vavalos5** [comment]
I'm including a screenshot to a mind map template Figma has that I think you can utilize which could make the variety of different types of data visualizations easier to read and follow.

![Image](https://github.com/grommet/hpe-design-system/assets/62117454/3a9a8c56-8aaf-48b9-b891-afee0d06c4db)

**Comment by kurt-ph** [comment]
@vavalos5 Thanks Vicky, I will try that figma template and look at the example you attached on the GitHub ticket. 

Sure, I can look into gathering relevant examples and screenshots to reflect the real use case as much as possible. I have most from HPE, but I'll look at other real life product examples for reference I can add. Some might be harder to find, as certain types of charts aren't used much in some digital products. Will try to find out as much as I can.

Let me know if you have any other suggestions or ideas.

**Comment by SeamusLeonardHPE** [comment]
Hey @kurt-ph @vavalos5 

I had a quick pass at creating a mind map template in figma today ( I needed a break from button order!)
Please review and let me know if this is helpful. My main goal was to simplify the appearance and act as a quick guidance/signpost to facilitate decision making, rather then getting deep into the complexity of the datatypes.

https://www.figma.com/file/HuUVMlbOx6Nrc9EgFCkHrY/Data-Visualization?type=design&node-id=2800-2234&t=6wsPUB8WLGt41wOl-4

Its incomplete in terms of copy and screenshots/examples but I thought it might help our discussion.

**Comment by kurt-ph** [comment]
@vavalos5 @halocline 
Included a link on the updated chart and reorganize the chart based on recent feedback:
https://www.figma.com/file/HuUVMlbOx6Nrc9EgFCkHrY/Data-Visualization?type=design&node-id=1%3A6&mode=design&t=mW76ggXpcR1a7RaH-1

**Comment by vavalos5** [comment]
Nice work Kurt! This decision tree is much easier to read and follow! Thanks for making changes 😄 ✨

**Comment by kurt-ph** [comment]
As we discussed before, I created the framework as the initial first step after getting team and individual feedback. Closing this ticket as we agreed in standup that this is complete.
