### ISSUE TITLE
Map - RESEARCH SPIKE - Compare and contrast map alternatives to LeafletJs

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#3394]
Parent issue: #3384

Time-boxed to 1 week.

## ToDos

- [x] Find 2-3 alternatives to LeafletJs.
- [x] Provide pros/cons for LeafletJS + 2 others
- [ ] Share-out findings

Research tracked in FigJam: https://www.figma.com/file/5wrkWT2NllOoInCWVHU4KY/Mapping-Options?type=whiteboard&node-id=0-1&t=fbpRIb6TNZEiIWyH-0
