### ISSUE TITLE
Map - Toggle view type button group in data collection toolbar

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#3432]
[Figma File](https://www.figma.com/file/bMVkdgHkimCENGHiKPGcYH/Maps?type=design&node-id=759%3A70337&mode=design&t=OnjbA4Urm04fBlWx-1)
## Problem Statement

How might we provide users the option to toggle between map and DataTable view to quickly and easily peruse through data collections according to preference.

## Summary

As a user managing or browsing data collections, I'd like the ability to toggle between data collection views according to my preference and need. Specifically, I'd like the ability to change between a map, chart, table, list, or grid view.

**ToDos**

- [x] Problem Statment
- [x] Collect use cases from GLCP and Storage
- [x] Collect examples, research and comparative analysis of other frameworks/examples
- [x] Explore incorporating a "view toggle" into the data collection Toolbar
- [x] How many views can/should a user be able to toggle between? Should it be exhaustive? Should it be limited?
- [x] When placed in the "view controls" region of the Toolbar, how should it be ordered when considering other view controls such as search, filters, manage columns, saved views, etc.

**Comment by vavalos5** [comment]
Are there any use cases that can be linked to this or where the need is coming from? I believe I can only think of one that we discussed with Matt from GLCP team - the option to view DataTable.

**Comment by vavalos5** [comment]
I have reached out to Darren, Winnie and Aideen for use cases and awaiting a response. 
I'll begin comparative analysis tomorrow and create a problem statement.

**Comment by vavalos5** [comment]
I've created a problem statement which can also be seen at the top of this ticket, collected use cases, conducted research, chatted with stakeholders and created [3 different variations of explorations, with two of them having second similar explorations.](https://www.figma.com/file/bMVkdgHkimCENGHiKPGcYH/Maps?type=design&node-id=761%3A73180&mode=design&t=ICeI3IzyAs1T8xlw-1) 

Would love to get your eyes and feedback on these @SeamusLeonardHPE @kurt-ph @ashifalinadaf @KennyAtHPE when you've got a chance. Thanks!

In addition, i've sent these to Winnie, Matt from GLCP, Sylvia, Darren and Aideen for feedback.

**Comment by vavalos5** [comment]
I've added examples of map/list, chart/datatable toggles in addition to the datatable/map toggle explorations.

**Comment by SOjaHPE** [comment]
@vavalos5  finally had a chance to review this ticket, the comments and catching up on the the figma file side of things.

Couldn't tell from your comments inline here or from the figma file whether you ever connected with Darren or Winnie or not, regrading their use cases. There were two examples from Storage (maybe you did connect) and two examples that have a similar toggle button to what GLCP is using.

Here is the link to the [Storage Toggle View Controller](https://www.figma.com/file/Grj0t94TGlZLJSkXdx7zWt/SC_ToggleViewController?type=design&node-id=1457%3A47&mode=design&t=bYXv8ctZr3sevhSq-1) figma file that details the widget they use to show the supported view types. You also note that they have a wide range of needs to support many different combinations of data collection types plus different diagram layouts/data visualizations based on the use case and needs.

If I remember the original problem statement at sprint planning was a bit more open to provide our users the ability to toggle between different data collection views. Now that problem statement is a bit more rigid and doesn't have the same flexibility.

Id recommend that you rescind your invitations to Winnie, Matt from GLCP, Sylvia, Darren and Aideen for feedback. Since there wasn't enough information known when your option explorations were made and there seemed to be a change made to the problem statement. It would be good to come to a decision on the direction and problem statement within the team before socializing externally, don't want to waste anyone's time.

- Also, my input regarding the placement of the view toggle controls..it would be easy to just lump them in w/ the left aligned view controls. But it would be good to consider the fact that it is realistic for data collection toolbar controls to change out based on the different type of data collection or data visualization. That would mean that the view/action controls would be contextual to the view type, so just keep that in mind w/ your explorations once you get to that part of the ticket.

**Comment by SOjaHPE** [comment]
@vavalos5 - Guess in my head, during the mtgs w/ GLCP PM about Maps and the tie to support a tabular data collection layout. I thought of this as a broader need to togging between views in general. Expectations might be based on my familiarity with Storage and their use cases toggling between data visualizations, calendars, data collections. ETC.

My only recommendation is that we know there will be a need for flexibility with how our customers utilize this widget based on their use cases/needs. Storage and current use cases sort of illustrate this. It would be best to avoid tightening the work so much that it only covers one known use case but to word it so the pattern can be leveraged. Data collection types... Data Visualization types.. etc. - Do you see the benefit w/ this approach, do you see any cons? I feel we'd have to revisit it if we just solve for your current problem statement.
We can chat about more, if needed.

**Comment by vavalos5** [comment]
Two additional explorations have been made for [Map/DataTable view (https://www.figma.com/file/bMVkdgHkimCENGHiKPGcYH/Maps?type=design&node-id=761%3A73180&mode=design&t=NZ7LPJeC8T9YH4Tj-1).

**Comment by vavalos5** [comment]
Inserting a screen shot of direction based on a conversation I had with Scott. I've re-introduced the border to the buttons at the toolbar level. I was also informed by Scott that we're making an enhancement to the theme to add the border back to the toolbar buttons and have reached out to Taylor on what that might look like. Previously we had the 1px border with default border stroke so i've applied that here.

I'm including two screen shots where only the toggle button group have a border and a second where all buttons at the toolbar level have a border. In addition, i'm proposing the filter be to the left of the DataTable Customization button so it is closest to the search input (not a part of this scope but something I noticed).

![Image](https://github.com/grommet/hpe-design-system/assets/62117454/9bb1de36-f485-4eca-a19c-1f0eba86bb44)
![Image](https://github.com/grommet/hpe-design-system/assets/62117454/cdd037cb-5e4c-4e0c-8b1f-4b2f1d2c86dd)

**Comment by vavalos5** [comment]
One question i've been asking myself is whether the button group should live close to the other toolbar level buttons or if it should live closer to the action menu button when there is one.

Things can get busy on the left but it almost looks a bit lost on the right.

![Image](https://github.com/grommet/hpe-design-system/assets/62117454/6d70ded4-a8d8-429b-b3d9-9d45277cb975)

**Comment by halocline** [comment]
> Two additional explorations have been made for [Map/DataTable view](https://www.figma.com/file/bMVkdgHkimCENGHiKPGcYH/Maps?type=design&node-id=761%3A73180&mode=design&t=NZ7LPJeC8T9YH4Tj-1).

A link taking me directly to the "two additional explorations" would be helpful. I am unclear where I should be looking. Bonus points for a brief summary describing what new territories these explore.

**Comment by halocline** [comment]
> Inserting a screen shot of direction based on a conversation I had with Scott. I've re-introduced the border to the buttons at the toolbar level. 

I think the "toggle button group" treatment is a variant we should move forward with. As well as a variant like option 1.1 when the group might be unnecessary.

Question:
- The screen shot makes it look like the active item in the toggle button group is the chart view, but a table is being displayed. Should the table icon be the button receiving active state?

**Comment by halocline** [comment]
> I was also informed by Scott that we're making an enhancement to the theme to add the border back to the toolbar buttons and have reached out to Taylor on what that might look like.

This is an open question which has not been decided. We have received feedback from some stakeholders that the borderless buttons can get lost. This exploration will be handled in separate scopes of work. I'd like to ensure we are hitting Glasgow dependencies prior to re-examining v5 theme changes. This will also allow folks a bit more chance to acclimate to the v5 theme - and opportunities for us to collect feedback.

**Comment by halocline** [comment]
> In addition, i'm proposing the filter be to the left of the DataTable Customization button so it is closest to the search input (not a part of this scope but something I noticed).

I'm open to this proposal. Can you elaborate on your reasoning behind this proposal? This is what I have been referring to as our "design rationale." Essentially our explanation for how we arrived at particular design choices. This is helpful when we need to revisit why we made certain decisions, to communicate to stakeholders, and to not lose site of our reasons if we want to make adjustments in the future -- that way we aren't accidentally losing something we originally were solving for.

**Comment by vavalos5** [comment]
Based on the research i've gathered, placing the filter to be closest to the search is more intuitive and a common place where a user would expect it to be placed. They reduce cognitive overload for a user and are expected to be synchronously connected to the results that they're acting upon.


Sources: 
https://www.smashingmagazine.com/2021/07/frustrating-design-patterns-broken-frozen-filters/
https://www.nngroup.com/articles/filters-vs-facets/

**Comment by halocline** [comment]
> To clarify, are we moving forward with the buttons with the borders? I want to make sure I adjust them correctly.
> 
> @halocline

To be determined. For the time being. We can leave the toolbar buttons as they are currently. We will create a specific issue for updating them if that is the direction we end up going.

**Comment by vavalos5** [comment]
Based on that, I believe this ticket is complete. Let me know if good to close.

**Comment by halocline** [comment]
> Based on the research i've gathered, placing the filter to be closest to the search is more intuitive and a common place where a user would expect it to be placed. They reduce cognitive overload for a user and are expected to be synchronously connected to the results that they're acting upon.
> 
> Sources: https://www.smashingmagazine.com/2021/07/frustrating-design-patterns-broken-frozen-filters/ https://www.nngroup.com/articles/filters-vs-facets/

So how I would like to improve upon this is specifically state the reasoning and rationale. This is incomplete. This supplies a reference, but no reasoning. I will respond with more detail tomorrow.

**Comment by halocline** [comment]
> Based on that, I believe this ticket is complete. Let me know if good to close. @halocline

Can you please point me to where the recommendation and design rationale are for:
- [ ] How many views can/should a user be able to toggle between? Should it be exhaustive? Should it be limited?

Can you please point me to where the recommendation and design rationale are for:
- [ ] When placed in the "view controls" region of the Toolbar, how should it be ordered when considering other view controls such as search, filters, manage columns, saved views, etc.?

For both of these, I would like a clear link to or expression in this issue an explicit answer to these questions. Explicit answer = recommendation + reasoning.

I recognize that this expectation may be different than what was previously asked for. We are upping are game.

**Comment by halocline** [comment]
> Based on that, I believe this ticket is complete. Let me know if good to close. @halocline

I would like these items complete before closing: https://github.com/grommet/hpe-design-system/issues/3432#issuecomment-1614096205

**Comment by vavalos5** [comment]
> > Based on the research i've gathered, placing the filter to be closest to the search is more intuitive and a common place where a user would expect it to be placed. They reduce cognitive overload for a user and are expected to be synchronously connected to the results that they're acting upon.
> > Sources: https://www.smashingmagazine.com/2021/07/frustrating-design-patterns-broken-frozen-filters/ https://www.nngroup.com/articles/filters-vs-facets/
> 
> So how I would like to improve upon this is specifically state the reasoning and rationale. This is incomplete. This supplies a reference, but no reasoning. I will respond with more detail tomorrow.
> 
> Brief insight:
> 
> * having to explicitly state reasoning in text has many benefits
> * the writing process forces us to clarify, refine, and solidify our thinking
> * it turns intangible/feelings into tangible/rationale
> * the process of editing and refining our thoughts = greater clarity
> * greater clarity = opportunity for greater insights
> * greater insights = greater innovation
> 
> This ask is a "push for better"
> 
> Additionally, I do not see this recommendation executed in the proposed designs.

I'm not sure I understand. I'm adding a screenshot of the reasonings i've included in the designs I created and mentioned yesterday. Can you please clarify on what else you're expecting. Having clear guidelines set would be helpful in the beginning of the ticket so we can meet the asks. @halocline @SOjaHPE 

To add, this was an ask and mention from @Oja, Scott on placing the filter button to the left of the DataTable Customization as it is a common pattern. 
![Screen Shot 2023-06-30 at 8 52 03 AM](https://github.com/grommet/hpe-design-system/assets/62117454/4d03ff31-ee9b-4082-8515-8f47932b35cf)

**Comment by vavalos5** [comment]
Guidelines draft can be found here. I'm including a screenshot as well that provides more clarity on design rationals in regards to the placement of the button, how many buttons there could be. 

In addition, I took this a step further and provided anatomy, description of what the toggle button group is, when to use, when not to use, guidance, other use cases and best practices. [Find link here](https://www.figma.com/file/bMVkdgHkimCENGHiKPGcYH/Maps?type=design&node-id=955%3A88206&mode=design&t=j6JSFs7xtsoA3QP5-1). @halocline 



![Image](https://github.com/grommet/hpe-design-system/assets/62117454/b8815d23-ca29-43ec-8edc-bc2fc8e60dd9)

**Comment by SOjaHPE** [comment]
@vavalos5 thank you for updating the ticket - Matt will reply regarding the three acceptance criteria items.

As far as the guidelines. I'd recommend creating a follow on ticket to track this next deliverable. Below are my thoughts.
**RE: posting the draft of the guidance.** My suggestion with that would be to approach the toggle button component guidance from a bit more generic approach. This would allow you to focus on 'what' it is used for, 'why' a consuming designer would pick this type of compound button over a switch or a checkbox, etc. 
https://mui.com/material-ui/react-toggle-button/   here is a good example of an existing toggle button spec that should inspire. This button variation is common in most design systems and it has a wide range of uses. Get into the specific use cases when appropriate, in the usage examples, do's/don't.  A great starting point to expand upon later as new use cases come to light but right now as an MVP component guideline it can be lean. To the point.

**Comment by halocline** [comment]
@vavalos5 @SOjaHPE @SeamusLeonardHPE : This is the direction I think we should go in terms of "data collection toolbar" and the relative placement of the "view toggle control."

I need to fill in the rest of the rationale for the nested elements and action controls, but this should provide an idea for the overall thinking.

I'm open to how this is represented in Figma, but would like the fundamental elements of:
- Tell me what I am looking at, who the author/owner is, and when it was last modified
- Give me the recommendation - the design decision - the "what"
- Then tell me the design rationale - the "why"

**Comment by halocline** [comment]
@vavalos5 @SOjaHPE @SeamusLeonardHPE -- Looks like I didn't paste the link correctly. So my comment above was lacking detail to make any sense. Here's the link: https://www.figma.com/file/mFue4ysWDmBdxIeRKffeOo/Data-collection-toolbar?type=whiteboard&node-id=1-204&t=H1ztMXSJfuJraTDo-4

**Comment by SeamusLeonardHPE** [comment]
Hey @halocline @SOjaHPE 

Related to this ticket, and [#3481 ](https://github.com/orgs/grommet/projects/12/views/1?pane=issue&itemId=33695088)

As we build out templates to standardise our research & findings documents I looked at this ticket to raise some questions  and to see if my draft can help with resolving this ticket or understand what is missing.
@vavalos5 excuse if this is a crude summary of your work and investigation which seems thorough and thoughtful. My aim is to work towards a format we can use to deliver our finding and assist with sign off. 

@halocline my list of topics for 'design rational' is not exhaustive, so I would appreciate input on how best we can frame our 'design rational', if we have a list of considerations to measure against it will help the process, not just the summary.

@SOjaHPE , in relation to your comment re 'guidance form a more generic approach', I attempted to describe this design pattern at a higher level, but we do need to be specific as to how the design decision solves this ticket in particular. 


Very rough draft for discussion.

https://www.figma.com/file/bMVkdgHkimCENGHiKPGcYH/Maps?type=design&node-id=1359-91558&mode=design&t=F2z7YeFKKuyGfHti-4

**Comment by vavalos5** [comment]
Thanks @SeamusLeonardHPE for creating a draft. [It looks very similar to the one I've created here](https://www.figma.com/file/bMVkdgHkimCENGHiKPGcYH/Maps?type=design&node-id=1260%3A91540&mode=design&t=3bMvJqCmUDTK6tTo-1). Would be great to have a discussion on how we'd like to lay this out and where it'll live.

**Comment by vavalos5** [comment]
Please find [Design Rational artboard within Figma here.](https://www.figma.com/file/bMVkdgHkimCENGHiKPGcYH/Maps?type=design&node-id=1260%3A91540&mode=design&t=7Rt2PJH3B5qMA68p-1)

I wasn't too sure if I captured the "saved preferences" correctly as i'm not entirely sure i'm familiar with the use cases. But tried my best to make a bit of a guess here. 

@halocline let me know your thoughts, thanks!

**Comment by vavalos5** [comment]
7/26 update:

- Scott mentioned he'd take a look during Sprint Planning Refinement
- Pinged Matt to take a look when he has a chance.

**Comment by halocline** [comment]
> Please find [Design Rational artboard within Figma here.](https://www.figma.com/file/bMVkdgHkimCENGHiKPGcYH/Maps?type=design&node-id=1260%3A91540&mode=design&t=7Rt2PJH3B5qMA68p-1)
> 
> I wasn't too sure if I captured the "saved preferences" correctly as i'm not entirely sure i'm familiar with the use cases. But tried my best to make a bit of a guess here.
> 
> @halocline let me know your thoughts, thanks!

Thank you @vavalos5 -- I think we are super close. I left a few clarifying comments in the file. For the purpose and scope  of this issue I think we have the recommended toggle styling, number of toggle options, and toggle placement within the toolbar -- which is what we needed. For future work, @SeamusLeonardHPE , we should find a place for this toolbar work to live and be expanded upon. This sets us up nicely for building upon in the future.

**Comment by vavalos5** [comment]
I've revised the comments left on the file.


I've included the following:

- a wireframe of the toolbar
- changed "Saved Preferences to "Save Views"
- I do have some questions in regards to the subitems we've added on the Customization Controls such as the "group by" and the "sort". Not entirely sure Those are needed here at this level or maybe I need more clarification.
- made suggested modifications to the content in the recommendations part

Let me know your thoughts @halocline

**Comment by vavalos5** [comment]
Ready for final review @halocline from your last comments.

I've modified the wireframe example so that the find controls, saved views and customization controls are within the view controls section.

I've added your explanation of "sort" under "customization controls".

**Comment by SOjaHPE** [comment]
@vavalos5 just reviewed your rational and guidance, everything looks great. Inserted a few comments in the toolbar guidance section. Think this is going to be resolved and closed out today. Let me chat with @halocline about a few items.

**Comment by vavalos5** [comment]
Awaiting on final verdict of where sort should live.. In "Find Controls" or "Customization Controls"

**Comment by halocline** [comment]
Good to close.
