### ISSUE TITLE
Pagination - Define pagination responsive behavior

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#3439]
The pagination control is overflowing on smaller screensizes.

Sherry raised a question regarding how the pagination and page select control works on smaller screensizes.

![image](https://github.com/grommet/hpe-design-system/assets/135040188/58d49360-1d02-4ea6-aada-34ccbb09e208)

Suggested fix from Sherry
![image](https://github.com/grommet/hpe-design-system/assets/135040188/ac69ce6f-2bdb-47d2-a249-a2dbc86250e7)

Responded to by Matt & had a call with Vicky & Kenny. Consensus was that we should make sure all elements are left aligned at smaller break points. 

We need to address the horizontal padding between page select and the text returned number of items, and what the responsiveness looks for each breakpoint.

<img width="955" alt="image" src="https://github.com/grommet/hpe-design-system/assets/135040188/89c8c7b6-9868-4f31-a16e-4753fbc6657a">

Nites from Matt 
"A couple other levers we have:
Pagination has properties we can tweak such as numberMiddlePages which affect the overall width of the pagination control.
Spacing, Grommet has responsive spacing built in which automatically decreases (pad, margin, gap) by half when transitioning from medium --> small breakpoints.
Small notes:
When pagination control drops to second row, the right alignment seems off. Perhaps left-align or center at that breakpoint.
Questioning the order of the “number items” control and “showing summary” — would need to play with this a bit."

https://hpe.slack.com/archives/C04LMJWQT/p1687446319503979

-------------------

**ToDos**
- [x] Define what controls make up "pagination" (e.g. page size selector, data summary, page selector, etc.)
- [x] Define placement/order/positioning/alignment within the larger "pagination" container
- [x] Assign priority to each control
- [x] Define responsive behavior (e.g. how do the controls respond in relation to one another? do individual controls have internal responsiveness?)
- [x] Support all recommendations/decisions with guiding principles and design rationale
- [ ] Create issue - "Create coded prototype of responsive pagination behavior"

**Comment by SeamusLeonardHPE** [comment]
First draft with some experimental updates on the pagination component.

Considerations:
- Create component set and use variant properties
- Add "Show x rows" control (should this be component)
- Responsive variants set at smallest breakpoint dimensions
- TBD share with devs to improve naming conventions and logic

https://www.figma.com/file/IfSqGbFNoesRmspjpNyZws/%233439---Define-responsive-behavior?type=design&node-id=2924-10756&mode=design&t=wU7OLKcuf1tLjuMx-4

@halocline @KennyAtHPE you folks both responded to the initial request from Sherry, a quick review to see if this is the correct direction would be appreciated

**Comment by KennyAtHPE** [comment]
Connected w/ Seamus on current recommendations and talked about the next steps.

**Comment by KennyAtHPE** [comment]
Left some comments on both of the links. It's looking good!

**Comment by SeamusLeonardHPE** [comment]
Created follow on ticket for responsive prototype

[https://github.com/grommet/grommet/issues/6923](https://github.com/grommet/grommet/issues/6923)

@taysea
