### ISSUE TITLE
SelectMultiple - Create figma variant to support 'Create/Add' action

### ISSUE THREAD

**Issue by SOjaHPE** [grommet/hpe-design-system#3477]
Main ticket- [#2887](https://github.com/grommet/hpe-design-system/issues/2887) that provided the recommendation supporting the Creating or Editing CRUD action use cases within the SelectMultiple component. For use cases when a user is unable to find an expected item in a list. The user should be able to easily '_**add**_' or '_**create**_' a new list item with-in the SelectMultiple component.

**ToDos**

- [x] Before touching any components or creating hi-fi wireframes - storyboard the interactions and ux flow of the interactions associated with options:

1. Having the select's dropdown to do the work
2. The select is "dumb" and simply serves a defined 'control' as a routing mechanism presenting a modal or other screen

- [x] Before modifying the existing figma component, create a plan and specification for the modifications that will be required to be made to the figma component.
- [x] Identify new properties or variance that would need to be added to support this new feature.
- [ ] Verify the proposed specification is in alignment/parity with the grommet work that needs to happen
- [ ] Confirm the placement and styling of the new control in the SelectMultiple figma component
- [ ] Confirm the suggested interaction/behaviors and containers to surface and render the new input field and save it
- [ ] Request reviews/feedback in-order to finalize the above

**Deliverables**

- [ ] Create the new SelectMultiple figma component version supporting the new functionality
- [ ] Create follow on issue for Grommet to extend the SelectMultiple component to allow for a custom action button to be appended to the select's drop

**Comment by halocline** [comment]
@SOjaHPE - Is this limited to "add" or should "edit" be in scope? For example, I have a list of labels as options, but instead of adding an additional label option, I want to edit an existing option.

**Comment by SOjaHPE** [comment]
@halocline fair question. My first instinct was to keep it simple and limit it to 'Create/Add' since the follow on design work is a bit more complicated for use cases when multiple list items are selected. I'm open to it, if we want to cover both 'add' and 'edit'.

**Comment by halocline** [comment]
Reading the comments in the preceding issue. I think we really need to nail the UX flow (think storyboards) before touching any hi-fi prototypes and component implementation. Specifically, I am not clear whether we are asking the select's dropdown to do the work, or should the select be "dumb" and simply serve as a routing mechanism presenting a modal or other screen?

See: https://github.com/grommet/hpe-design-system/issues/2887#issuecomment-1641188920

Regardless, this work should be a designer/developer collab, led by the designer. There are a lot implementation details and probing questions which need to be collaboratively discussed.

**Comment by SOjaHPE** [comment]
@halocline I've updated the ToDos to reflect the comments. Thanks for pointing out the two methods. I'm leaning towards - "the select should be 'dumb' and simply serve as a routing mechanism presenting a modal container, keeping the user in context w/ that task" from a simplicity aspect. Would be more flexible and scalable.

**Comment by ashifalinadaf** [comment]
Picking up this ticket. 
Initially as said, I will be working on the '**storyboard the interactions and UX flow of the interactions associated with options:
1. Having the select's dropdown to do the work.
2. The select is "dumb" and simply serves a defined 'control' as a routing mechanism presenting a modal or other screen.**

**Comment by vavalos5** [comment]
Asif, thank you soooooo much for breaking down your work and steps - it is very helpful to see some of the options you're learning towards. I left some comments on your Figma file. In general, I think it would be helpful to think about this from an accessibility stand point and how you imagine someone with a vision impairment navigate the create/add option from a keyboard and screenreader perspective. 

Would be happy to connect you with Bill Tipton who is our accessibility point of contact when it comes to questions like these. Let me know if I can help. 😄

**Comment by SOjaHPE** [comment]
@ashifalinadaf since this is still in progress and you've made significant progress, do you mind updating the description todo's and deliverables to check off completed work to better track the current status.

Since our sync up, wanted to confirm this is were things are left:

- Plan is to move forward with the #2 Dumb component option, selectMultiple is solely serving as a launching point, simple and easy to allow product teams to connect to the appropriate flow to support the creation of their new string, object or entity.
- Reference previous [WIP v3 w/ Documentation Accessibility section](https://www.figma.com/file/EcLSFz5L7EwmOadmEYGshZ/SelectMultiple-Component?type=design&node-id=2178%3A23519&mode=design&t=NZjwx0izofHJl4ae-1) content in the SelectMultiple figma file where detailed documentation for the screen reader, tab order, and keyboard commands were captures for SelectMultiple component interactions. Use those as a reference to help document how the new 'Create/Add' control enhancements should be accessible. Once those are created it is at a good point to use those artifacts to review with @jcfilben 
- Create a follow up ticket to track work related to firming up 'control' wording - when to use ‘add’, ‘create’, ‘new’.

**Note:**
- Grommet’s select component already has the capabilities to ‘create’ a new option, review that component in the grommet storybook to see the behaviors. If that will be useful.

Let me know if you have any feedback with next steps to set expectations for Sprint Planning tomorrow. Thank you

**Comment by SOjaHPE** [comment]
@ashifalinadaf thank you for the update. Moving forward please checkoff and update the ticket description todo's and deliverables section yourself as the ticket work progresses.

**Comment by ashifalinadaf** [comment]
Following steps have been completed and need to be documented. 

- [ ] Before modifying the existing figma component, create a plan and specification for the modifications that will be required to be made to the figma component.
- [ ] Identify new properties or variance that would need to be added to support this new feature.

Next steps will be covered in the follow up ticket https://github.com/grommet/hpe-design-system/issues/3507

**Comment by ashifalinadaf** [comment]
Closing this as deliverables are covered in next ticket #3507
