### ISSUE TITLE
Data collection toolbar - Create coded prototype

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#3493]
Follow on from: https://github.com/grommet/hpe-design-system/issues/3432

**ToDos**
- [x] Responsive behaviors between controls (e.g. two distinct controls competing for space)
- [x] Responsive behaviors within controls (e.g. search input --> search button drop, saved view select --> icon button based drop)
- [x] Rules for when certain controls are displayed / not displayed (e.g. only show DataTableColumns when displaying DataTable view)

## Deliverables
- [x] Rationale/rules: Can be found in this comment: https://github.com/grommet/hpe-design-system/issues/3493#issuecomment-1668549063
- [x] Coded prototype: Here is the prototype (v1.b from the below comment) that was most highly voted amongst the team:
   - CodeSandbox: https://codesandbox.io/s/data-collection-toolbar-breakpoints-v1-b-ztzk7s
   - Deploy: https://ztzk7s.csb.app/
 
For other prototypes see comment below: https://github.com/grommet/hpe-design-system/issues/3493#issuecomment-1668549063

**Comment by taysea** [comment]
For the explorations below, the following rationale is driving how content responds:
1. Search/filter are the most repeatedly/frequently interacted with controls  so their space should be preserved for as long as possible. We will only shrink the search input on xsmall/small breakpoints.
2. Selecting a preset "view" is the next most important because this allows a user to establish some preset filters/data collection views/etc all at once. Show this when room and with more importance than the data collection toggle.
3. Toggling between data collection views is a nice feature, but isn't likely to be repeatedly interacted with. Show when room, but collapse to overflow otherwise.

Some other rationale:
1. Collapse controls into an overflow menu when there isn't room. Fully "removing" a control at certain breakpoints/when not room can create a confusing experience for continuity of capabilities/discoverability of controls.
2. Keep things in a single row to avoid clutter/taking up too much vertical real estate with controls. (this is current exploration, but wrapping is an option we could explore too)

## v1 (breakpoint driven responsiveness)

In this version, the breakpoint drives when content collapses. This is the "easiest" approach, but isn't as dynamic likely as we'd want. Even with the current content, things overlap at certain widths.


CodeSandbox: https://codesandbox.io/s/data-collection-toolbar-breakpoints-jfks75?file=/src/components/CustomizationControls.jsx

Deploy: https://jfks75.csb.app/

**Comment by halocline** [comment]
@taysea , I have reviewed and think this issue can be closed. We have the prototype which communicates our desires for when we go to code in Grommet Toolbar.

**Comment by taysea** [comment]
Great, thank you for reviewing. Closing this ticket.
