### ISSUE TITLE
Template library - Tracking issue

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#3535]
Tracking issue for template work.

### Controls
- [ ] ActionMenu
- [ ] ReverseAnchor
- [ ] ToggleButtonGroup

### Layouts
- [ ] ButtonGroup
- [ ] EmptyState
- [ ] LayerHeader
- [ ] ModalDialog
- [ ] SideDrawer

### Typography
- [ ] TextEmphasis

**Comment by KennyAtHPE** [comment]
**OLD DELIVERABLES FOR REFERENCE**

Tracking issue for template work.

## Desired Templates

### Controls
- [ ] ActionMenu
- [ ] ReverseAnchor
- [ ] ToggleButtonGroup

### Layouts
- [ ] ButtonGroup
- [ ] ContentContainer
  - [ ] https://github.com/grommet/hpe-design-system/issues/3501
- [ ] EmptyState
- [ ] LayerHeader
- [ ] ModalDialog
  - [ ] https://github.com/grommet/hpe-design-system/issues/3524
  - [ ] ModalDialog template - Published coded template
  - [ ] ModalDialog template - Guidance and examples added to HPE Design System site
- [ ] SideDrawer

### Typography
- [ ] TextEmphasis

**Comment by SeamusLeonardHPE** [comment]
This ticket aims to deliver a first draft of a design pattern library before the end of sprint.

We are to start designing form smaller organisms and on a following sprint we will assemble those into larger templates.

Phase 1 

- [ ] Chip
- [ ] Avatar + Notification
- [ ] Toggle button 
- [ ] Toggle switch
- [ ] Button Group
- [ ] Layer header
- [ ] Service header
- [ ] Breadcrumbs
- [ ] Reverse anchor
- [ ] Slider Control
- [ ] Progress Bar/Meter
- [ ] Data collection toolbar
- [ ] Table row


Phase 2

- [ ] Date Picker
- [ ] Form group
- [ ] Stepper
- [ ] Skeleton
- [ ] Table sticky header with overflow
- [ ] Table sticky 1st column with overflow
- [ ] Card variations


For visibility of other patterns that have been suggested/built via PAL & Sandbox
https://hpe-my.sharepoint.com/:x:/r/personal/seamus_leonard_hpe_com/Documents/Asset%20%26%20Template%20Review%20-%20PAL+SANDBOX.xlsx?d=w77af88ad44ea4da6a3787c5f27475ee1&csf=1&web=1&e=7zfk6V

**Comment by SeamusLeonardHPE** [comment]
@kurt-ph @KennyAtHPE 

Review existing design templates & add comments that are in the “construction” file, start with Side drawer & Center layer. 
@SeamusLeonardHPE will make edits based on feedback & copy over to the “public” file when agreed upon. 

[Center Modal](https://www.figma.com/file/CD8dd44QACAs5TmHB9trp8/Template-Library---Construction?type=design&node-id=129-4307&mode=design)  

[Side Drawer](https://www.figma.com/file/CD8dd44QACAs5TmHB9trp8/Template-Library---Construction?type=design&node-id=129-4306&mode=design)

### **Reviews will consist of **

1. **Fonts** - all fonts use HPE styles (button medium is an exception)
2. **Color** styles are use HPE styles
3. **Elevation** uses HPE styles (where applicable, not all containers require eg form groups)
4. **Padding, Gap, Border radius** - All should adhere to HPE t-shirt sizing - inspect containers & auto-layout groups for adherence. 
5. Do the templates **adhere to guidance** (e.g. button alignment, order, centre modal is for concise confirmations or dialogs etc) 
6. **Use components** - Is the template build using current components everywhere possible (note I have broken name value pair out of name value list)
7.  **Deprecated** - Comment on any “deprecated” components used, or nested inside published components.

Last check before adding to public library will include making sure auto-flow setting (fill/fixed) are all correct & consistent .

**Comment and discussion for furthering the project.**
- Gather and suggest other use cases for existing templates (Eg How else is side drawer used by other teams)
- Should we serve single list item, single name value pair - what’s the benefit of limiting access to the larger groups?
- Anywhere we are serving components that break guidance (eg checkbox group offers 15 checkboxes, max recommended is 5)
- What other common patterns can we build? Think containers for now cards.
- Where we have had to detach a component, or build a custom design add a note to see if the design could be brought into the Design System.
- What lessons learned, or external work can help us proceed.

 Complete the review & edits & announce the public library form Monday.

**Comment by KennyAtHPE** [comment]
Reviewed both the Side and Center layer pages
 1. **Fonts** - all fonts use HPE styles (button medium is an exception)
- Some areas are using Normal/default rather than Paragraph/default. Everything else is fine.
2. **Color** styles are use HPE styles
3. **Elevation** uses HPE styles (where applicable, not all containers require eg form groups)
4. **Padding, Gap, Border radius** - All should adhere to HPE t-shirt sizing - inspect containers & auto-layout groups for adherence. 
5. Do the templates **adhere to guidance** (e.g. button alignment, order, centre modal is for concise confirmations or dialogs etc) 
6. **Use components** - Is the template build using current components everywhere possible (note I have broken name value pair out of name value list)
7.  **Deprecated** - Comment on any “deprecated” components used, or nested inside published components.
