### ISSUE TITLE
HPE Theme - Stage all v5.1.0 updates and socialize

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#3536]
Now that the v5 theme has had a few weeks/months to live in GLCP, folks have had a chance to acclimate to the theme changes and provide feedback.

In GLCP there were a handful of local overrides to the theme made to satisfy stakeholder requests. These should be considered for officially incorporating into the HPE theme and/or refining the proposal. [The following are current overrides](https://github.com/grommet/hpe-design-system/issues/3536#issuecomment-1730499834).

### Prep/define changes
- [x] Connect with Chris Carlozzi to confirm on v5.1.0 styles. Use what is currently applied in GLCP override as a reference.
   - Additional changes to be made:
      - [x] Should Pagination buttons also be 600 weight like default? Yes
      - [x]  Update all button label weights from 500 --> 600 so visual hierarchy between secondary, default, and toolbar remains
      - [x] Should primary key of data table also be 500 weight like other emphasized text? Yes
      - [x] Should "small" button have dimensions sized down? Yes, size them down as they were in v4.
      - [x] Explore use of 600 weight on active tab
      - ~[] Get clarification from Chris on his mention of small tweaks to text and status colors. Are those values finalized? Should they be part of this minor release or a subsequent? @KennyAtHPE is also going to look at his own past explorations and work with Chris on this.~ We will leave the text colors as is for now since we did not hear back from Chris. The tweaks would be very minor adjustments to greys (low risk, easy to alter)-- so we can handle in future as necessary.
      - [x] Confirm text value color contrast on validation backgrounds.
      - [x] Should the xxlarge and greater text sizes be stepped down one notch since large and xlarge did? Leaving as is for now since no feedback has prompted changes. Also, these sizes are rarely used.
      - [x] In GLCP overrides, we stick with `400` weight at larger paragraph sizes, should we do the same for text as opposed to using `300` at larger sizes? Answer: xxlarge and above should remain at `300` so they don't compete with headings.
- [x] Create itemized list of changes: https://github.com/grommet/hpe-design-system/issues/3536#issuecomment-1728537457

### Socialize upcoming changes to critical stakeholders (Scott owning this)
- Small tweaks in color values and font-weights. Many of these changes have already been incorporated into Platform and are now finding their way officially into HPE theme.
- [x] Identify necessary stakeholders that should be notified of upcoming changes
   - Alyssa -- will help identify if all looks good, any others who should have eyes on it, etc.
   - GLCP (UX and UI)
      - [x] Salaija, Chiranjib, Annie Wu
      - [x]  Kyle Richardson and Gina (Global Header)
      - [x]   Alyssa Derek and Justin
      - [x]   Chesley R. - scheduled 10/26/2023
   - Compute Ops Manager
      - [x] Daniel Martin and Greg (connected over slack)
   - HPE Services
      - [ ]   Janice F,, Laurie Elliott, and Heidi Toshi - scheduled 10/30/2023
   - GLCS
      - [ ]   Harsha, Dhiim, Uma, Simon - scheduled 10/30/2023
- [ ] Send/demo [release preview notes and deploy](https://github.com/grommet/hpe-design-system/issues/3536#issuecomment-1730489350) to key stakeholders.

### Dev work (Taylor owning this)
- [x] Apply changes to grommet-theme-hpe as merged into NEXT branch: 
   - Changes are staged on NEXT branch, draft PR pointing to master when all changes have been finalized and approved: https://github.com/grommet/grommet-theme-hpe/pull/366
- [x] Consume on design system site and present to Chris Carlozzi and internal design system designer: https://github.com/grommet/hpe-design-system/pull/3549
- [x] Create release notes and change summary: https://github.com/grommet/hpe-design-system/issues/3536#issuecomment-1730489350
- [X] Apply NEXT branch to a GLCP instance and generate a [Vercel deploy preview](https://glcp-git-theme-5-1.greenlake-preview.com/home)
   - Mike will create this once all changes are finalized on our side.
   - Steps:
      - Remove ThemeContext.Extend values from ThemeMode.js
      - Point grommet-theme-hpe dependency to `https://github.com/grommet/grommet-theme-hpe/tarball/NEXT-stable`
- Publish release (To be done in a subsequent sprint): https://github.com/grommet/hpe-design-system/issues/3552

### Design work (Kenny owning this)
- [x] Create plan for how to apply changes to Figma components
   - Notify people before
   - Apply changes to assets (text sizing, colors, border styling, etc.) -- low lift given there is no component refactoring
   - Review with one other internal Design System designer 
   - Publish changes
   - Notify after release
- [x] Call-out any places where designer workflows may be affected by the changes/link to process for how designers would uptake the changes
   - Kenny to do some testing to see directly what this would look like for a designer consuming the changes
   - Add any findings to release/communication notes

### Internal review before publishing
- [x] Once dev and design work is staged, do internal review to ensure 100% alignment
- [x] Show n Tell share out on the theme changes (maybe set up a separate meeting w/ designers on what this process looked like)

### Post-release (TO BE COMPLETED IN FUTURE SPRINT)
- Communicate with Gina to confirm the latest text colors are accessible on `validation-ok`
- Announce/demo changes
   - Potential venues:
      - Sprint demo
      - Office Hours announcement
      - Design System Slack
      - Derek's stand up or other forums where we can speak directly
      - Cross-BU 
      - Email distribution list

**Comment by taysea** [comment]
(WIP) Based on discussions, here is an itemized list of what should be updated in HPE theme and in Figma:
- Colors
   - text:
      - dark: '#FFFFFF'
      - light: '#555555'
   - text-strong:
      - dark: '#FFFFFF',
      - light: '#333333',
- Button
  - default, secondary, and toolbar font-weights change to 600
  - toolbar border added back: border-width 1px, border-color "border", border-radius 6px
  - size "small" with label: vertical padding 5px, horizontal padding 12px
  - size "small" with label: remove custom 24px line height
  - size "small" icon-only: padding 7px
  - size "large" with label: vertical padding 10px, horizontal padding 24px
  - size "large" icon-only: padding 13px
  - size "xlarge" with label: vertical padding 21px, horizontal padding 30px
  - size "xlarge icon-only: padding 24px
- DataTable
   - primary key change weight to 500 
- Heading
   - Level 1 font weight change to 500
- Icon
   - size "large" 22px
   - size "xlarge" 24px
- Pagination
   - Button weight change to 600
- Paragraph and Text
   - size "large" change to font-size 22px, line-height 28px
   - size "xlarge" change to font-size 24px, line-height 24px, font-weight
   - size "xxlarge" change weight to 400
- Tab
   - Active tab font-weight 600
- Tabs
   - Extend bottom border of header across container width

**Comment by KennyAtHPE** [comment]
Figma release order
[ ] Publish text style and color style updates
[ ] Update all DS files
[ ] Publish component changes

*Updates should only be pushed once EVERYTHING else has been updated and changes are ready to be announced*

**Comment by KennyAtHPE** [comment]
[Figma sandbox](https://www.figma.com/file/gU8I1LS4ABABzE7A3tCDah/HPE-Theme---v5.X.X-Sandbox?type=design&node-id=0%3A1&mode=design&t=czYW7JvBOPi2uCLL-1)

**Comment by taysea** [comment]
## Release notes draft

- Refinement of text colors to slightly darker greys to increase contrast ratios.
   - `text` changed from `#6F6F6F` to `#555555` in light mode, and `#FFFFFFE6` to `#FFFFFF` in dark mode.
   - `text-strong` changed from `#444444` to `#333333` in light mode, and `#FFFFFFF5` to `#FFFFFF` in dark mode.

- Refinement of font-weights in button and tab controls to reduce use of bold in favor of semibold.
   - All button label and active tab font-weights updated from `700` (bold) to `600` (semibold). The exception is `primary` buttons which will continue to have a bold label in order to meet color contrast requirements on a HPE brand green background.

- Refinement of larger text sizes to slightly smaller values.
  - Anchor, Text, and Paragraph size `large` changed from `font-size 24px, line-height 30px` to `font-size 22px, line-height 28px`.
  - Anchor, Text, and Paragraph size `xlarge` changed from `font-size 30px, line-height 36px` to `font-size 24px, line-height 30px`.
  - To align with text styles, icons at size `large` and `xlarge` have been adjusted to `22px` and `24px`, respectively.

- Added back thin border around toolbar buttons to have parity with surrounding inputs.
- Added back bottom border on Tabs that extends the full-width of the container in order to give more visual boundary in layout between tab content and other page content.
- Reduced size of Button size `small` from 36px (same dimension as size `medium`) to 30px in order to provide greater visual hierarchy between button sizes. This aligns with the size `small` dimension from v4.

**Comment by taysea** [comment]
Current GLCP overrides for reference:

```
 // Temporary theme modifications for Discover 2023. Changes should be made in
  // grommet-theme-hpe once design is finalized.
  const modifiedTheme = deepMerge(hpe, {
    global: {
      colors: {
        text: {
          dark: '#FFFFFF',
          light: '#555555'
        },
        'text-strong': {
          dark: '#FFFFFF',
          light: '#333333'
        }
      }
    },
    button: {
      default: {
        font: { weight: 600 }
      },
      secondary: {
        font: {
          weight: 500
        }
      },
      toolbar: {
        border: {
          radius: '6px',
          width: '1px',
          color: 'border'
        },
        font: {
          weight: 500
        }
      }
    },
    heading: {
      level: {
        1: {
          font: {
            weight: 500
          }
        }
      }
    },
    paragraph: {
      large: {
        size: '22px',
        height: '28px',
        maxWidth: '25em'
      },
      xlarge: {
        size: '24px',
        height: '30px',
        maxWidth: '25em'
      },
      // This block applies size-specific weights to paragraph to ensure
      // that as paragraph sizes get larger, the weight decreases.
      // This block can be removed once grommet theme structure is enhanced
      // to support size-specific weights.
      extend: ({ size }) => `
        ${['xxlarge'].includes(size) ? 'font-weight: 400;' : ''};
      `
    },
    tabs: {
      header: {
        alignSelf: undefined
      }
    },
    text: {
      large: {
        size: '22px',
        height: '28px'
      },
      xlarge: {
        size: '24px',
        height: '30px'
      }
    },
    pageHeader: {
      // Needs to be removed after Grommet upgrade
      responsive: {
        breakpoints: ['xsmall', 'small']
      }
    }
  })
```

**Comment by taysea** [comment]
September 25 Update/Plan:
1. Finalize any modifications to text/status colors.
   - If there are any modifications, ensure text colors are accessible on validation backgrounds.
   - Make update to NEXT branch on grommet-theme-hpe: https://github.com/grommet/grommet-theme-hpe/pull/366
   - Make update to Figma staging.
2. Ask Mike to create Vercel deploy on GLCP. (Details listed in issue description checklist)
3. Have Scott present changes to key stakeholders (Details listed in "Socialize changes" section of issue description)
   - Suggestion to use Vercel deploy link and https://deploy-preview-3549--keen-mayer-a86c8b.netlify.app/theme-test
4. Once approval by key stakeholders, can progress with release on dev and design.
   - Release notes / changelog have been written.

**Comment by KennyAtHPE** [comment]
Connected w/ Chris on whether or not there were any modifications to the text + status colors. There weren't any changes on his end however he did mention possibly introducing a new status color to display informational content. That work is outside the scope of v5.1.
