### ISSUE TITLE
Figma feature: <Meter / Progress bar >

### ISSUE THREAD

**Issue by SylviaShenCC** [grommet/hpe-design-system#3596]
### What component does this request relate to?

Meter / loading indicators 

### Describe the feature you'd like to request.

We want to improve the user experience during extended wait times. The current spinner lacks clarity regarding status and progress, leading to user uncertainty. In our scenario, sending bytes to the backend takes 40 minutes, during which users should refrain from refreshing the browser to avoid interrupting the task.

<img width="941" alt="Screen Shot 2023-11-14 at 3 04 22 PM" src="https://github.com/grommet/hpe-design-system/assets/104940437/4a03d988-f649-4bdf-b4f2-15d8073a8ea6">
<img width="806" alt="Screen Shot 2023-11-14 at 3 04 39 PM" src="https://github.com/grommet/hpe-design-system/assets/104940437/da44fceb-9a75-4db3-bd40-9436ca0a29f4">

To address this prolonged waiting issue, in addition to notifying users about their task status, we recommend integrating a progress bar as a loading indicator. This visual element will provide users with a clear and immediate understanding of the ongoing process, including the estimated time remaining, thereby enhancing the overall waiting experience.

### Links to Figma files with use cases or ideations from you.

https://www.figma.com/file/B7JWZWAtsELg1tuoFh5xMp/Meter%2F-Progress-bar?type=design&node-id=1008%3A99&mode=design&t=8UFEnny0t7HRDcbh-1

### ToDos:

[] Review Sylvia's proposal for "upload meter / progress bar"
Make recommendation to adopt or not
Make recommendation as to where the contribution should live (component vs. template)
Review with developer(s) to discuss anatomy and potential API
Others?
Create follow on issues as appropriate for:
Adding "progress bar" to design system site
Publishing to Figma library

**Comment by ashifalinadaf** [comment]
Picking this up this ticket and reviewing the proposal.

**Comment by ashifalinadaf** [comment]
Limiting the scope of this ticket to the following items,

- [ ] Review Sylvia's proposal for "upload meter / progress bar"
- [ ] Make recommendation to adopt or not
- [ ] Make recommendation as to where the contribution should live (component vs. template)
- [ ] Review with developer(s)

**Comment by ashifalinadaf** [comment]
Please have a look at the initial recommendations for the progress bar 
@SeamusLeonardHPE @KennyAtHPE 

Need inputs from devs as well - @halocline @taysea 

[Figma link ](https://www.figma.com/file/0ozAw4JwXsFpOwu9T5OEDh/Progress-bar-for-review?type=design&node-id=1-3710&mode=design&t=TsixkvMGALlDEsJQ-11)

**Comment by halocline** [comment]
> Please have a look at the initial recommendations for the progress bar @SeamusLeonardHPE @KennyAtHPE
> 
> Need inputs from devs as well - @halocline @taysea
> 
> [Figma link ](https://www.figma.com/file/0ozAw4JwXsFpOwu9T5OEDh/Progress-bar-for-review?type=design&node-id=1-3710&mode=design&t=TsixkvMGALlDEsJQ-11)

Comments by @taysea , @SeamusLeonardHPE , and myself in the file.
