### ISSUE TITLE
BUTTON - Explore concept of a "ghost button"

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#3620]
Based on feedback from Office hours there has been numerous request for us to add a new variant to the existing button component.

Product designers have expressed the desire to have a "ghost" type button that can be used in in cased where the current default button style is not visually strong enough / results in perceived alignment issues with surrounding content, and the use case does not support using a secondary of primary style.

We will need to consider during discovery this is a visual alternative to default, so a sibling in terms of hierarchy, and document our recommendations. 

**ToDos**
Part 1 - Explore and present style options:
- [ ] Explore 2-3 options along with required states for a new button variant. (e.g. perhaps one with outline and another alternative with a light background)
- [ ] Share out with Design System team
- [ ] Depending on feedback and timing, consider breaking Part 2 and 3 into their own focussed issues

Part 2 - Clarify when/how a "ghost button" is used and ensure Brand buy-in:
- [ ] Document the naming conventions and use cases. (please clarify what the expected deliverable scope is here)
- [ ] Connect with Lozzi / Joelle / Ashley to evaluate from a Brand perspective
- [ ] Share out options with broader team ember to socialize and seek feedback (does "broader team" equal Experience Studio designers? Other?)

Part 3 - Create subsequent issues to integrate in the Design System:
- [ ] Ghost Button - Add  to Figma library
- [ ] Ghost Button  - Add as Grommet / HPE theme variant
- [ ] Ghost Button - Document variant on Design System site w/ supplementary when to use guidance

**Comment by taysea** [comment]
Closing, stale.
