### ISSUE TITLE
Figma release tracking

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#3767]
Tracking changes made in merged branches to facilitate batch publishing of library modifications.

Change log so publisher can track impact of including various updated components.
Recorded here since the publishing process provides no visual diff in figma. 

This is a trial run of how we can track merged changes and mirror monthly release patterns with grommet.

**Comment by SeamusLeonardHPE** [comment]
Readonly branch merged Mar 1st

### Related ticket:
https://github.com/grommet/hpe-design-system/issues/3635

### Changes made
- Changes to styling on text input component
- Addition of button to allow user to copy readyonly content from input field
- Creation of visibility boolean property to show & hide copy button on readonly variant only

### Bugfixes made
- Updated all "required" label text styles to Text/Medium/Xsmall to match all other inputs
- Updated info & error message layers text color to the correct dark style to dark in places where it was using light.


### Change impact

- Layer component, side drawer variant was affected by changes.
- This component consumes the "required" variant of textinput. The text style change altered the line-height from 20px to 16px.
- Impact can bee seen in screenshot below, **this was expect behaviour.**



![Image](https://github.com/grommet/hpe-design-system/assets/135040188/bfbd738a-4e0a-4161-bb69-e602ec8173c3)

**Comment by SeamusLeonardHPE** [comment]
Notification/Layer update - 

### Related ticket
https://github.com/grommet/hpe-design-system/issues/3727


### Changes made

- This was a follow up task to the notification refactor linked above.
- The updated notification component had not been accepted into the "Layer - Canter" componnent. 
- This was a result of the notifications component originally being in an external file, is has since been merged to the main library

### Change impact

- Layer component (center variant) will show as having been modified.

### Expected behaviour

- Canter Layer is ready to be published

<img width="438" alt="image" src="https://github.com/grommet/hpe-design-system/assets/135040188/9ad09054-32df-4b66-98e3-13d186fa04e2">

**Comment by SeamusLeonardHPE** [comment]
Merged in changes from https://github.com/grommet/hpe-design-system/issues/3740

### Changes made

- Added new states

Light / Checkbox Checked / Disabled
Dark / Checkbox Checked / Disabled

### Changes impact

### Publishing notes

- is ready to be published

![Image](https://github.com/grommet/hpe-design-system/assets/135040188/24adc475-73ce-41a0-88fb-5f5ebdc28e90)

**Comment by KennyAtHPE** [comment]
Merged in changes from #3741 

### Changes made

- Various alignment changes such as spacing, padding, and general resizing
- No breaking changes were made


### Changes impact
- DateInput component

### Publishing notes

- DateInpute branch merged and ready to publish
- #3635 is another branch created for readOnly update for DateInput

**Comment by SeamusLeonardHPE** [comment]
Merged in changes from figma branch "#3635 - DateInput readOnly update"

### Changes made

- Updated readonly state for Dateinput to match recent style & functionality updates on textinput
- Removed calander visibility for readonly & disabled varinats

### Changes impact

- DateInput component only

### Publishing notes

- Expected change - image below

<img width="483" alt="image" src="https://github.com/grommet/hpe-design-system/assets/135040188/b42d98da-c3c9-4d15-9593-08eec4286951">

**Comment by KennyAtHPE** [comment]
Merged in changes from figma branch #3635

### Changes made

- Global Header component updated to match the current implementation. Variants updated/added
     - GreenLake + console
     - Central on Prem
     - GreenLake on Prem
     - MSP
     - MSP Tenant
     - Generic HPE Product

### Changes impact

- Global Header component only

### Publishing notes

- Stack (icon for notification w/ badging) is misaligned.
- Further review from Chris on the HPE Product and special logo variants is to be done in a separate ticket

**Comment by SeamusLeonardHPE** [comment]
Merged in changes from [#3651](https://github.com/grommet/hpe-design-system/issues/3651)

### Changes made

- Refactored pagination component.

### Changes impact

- [Deprecated outdated pagination component](https://www.figma.com/file/slRqNvhJub0QlgN46zSXoY/HPE-Pagination-Component?type=design).
- [Added new replacement to main library](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?type=design&node-id=26125-326&mode=design)

### Publishing notes

- Dark mode has not been added as a variant property as it will become available of the Variable//Tokens work

**Comment by SeamusLeonardHPE** [comment]
Merged in changes from [#3717](https://github.com/grommet/hpe-design-system/issues/3717)

### Changes made

- Modification to  .RadioButton which was using a nested sub component that was linked to external file & using outdated brand styles.
- Edit to RadioButtonGroup height.

### Changes impact

- Changes to layer sub component inherited in published RadioButtonGroup component.

### Publishing notes

- Changes may lead to deletion of over rides in text field, but will not impact .RadioButton state prop which remains unedited.

**Comment by SeamusLeonardHPE** [comment]
@KennyAtHPE 
All merged updates here are ready to be published & announced on Monday.
Thanks.

**Comment by KennyAtHPE** [comment]
3/18 update: @SeamusLeonardHPE I've created a separate ticket for the extended-release notes to try and make it a bit more digestible #3799 

- [x] Reviewed all components
- [x] Updated radiobutton + radiobuttongroup based on [Betty's request](https://hpe.slack.com/archives/C04LMJWQT/p1710792770508679)
- [x] Updated Select based on [Tale's request](https://www.figma.com/file/Lh01flLH73cFNGZiFxEFth/HPE---Office-Hours?type=design&node-id=7034%3A1216&mode=design&t=gdHP2urQhUK2mh9E-1)
- [x] Removed external sub-component from checkboxgroup similarly to what was done to radiobuttongroup
- [x] Slight additional changes requested from Gina on Global Header
- [x] Published and announced component updates 
- [ ] Create follow-on tickets for leftover changes/fixes
