### ISSUE TITLE
DataVis - establish the colors we should use for dataVis.categorical

### ISSUE THREAD

**Issue by oliverHPE** [grommet/hpe-design-system#4042]
For categorical dataVis colors, determine if we are going with the existing 5 or Joelle's proposed 7.

NOTE: It has been decided we will use Joelle's proposed 7 based on positive feedback received in Sustainability Dashboard testing.

Deliverables:
- [x] Ensure proper color contrast from step to step: https://github.com/grommet/hpe-design-system/issues/4042#issuecomment-2334270921
- [x] Add appropriate color tokens
- [x] Create issue to do grommet-theme-hpe release with updated colors: https://github.com/grommet/hpe-design-system/issues/4175
- [x] Create issue to update Design System colors page with latest colors: https://github.com/grommet/hpe-design-system/issues/4176

**Comment by joellegregory** [comment]
https://www.figma.com/design/QXcCKvgzJpfaOTzu7F7AEn/Data-Visualization?node-id=1490-6252&t=qG4p7y5K7GrPfgPy-1

**Comment by taysea** [comment]
Still establishing values to meet color contrast requirements.

**Comment by joellegregory** [comment]
https://www.figma.com/design/N8hC3gZtlqMcOsOxWQoHhB/Data-Visualization-Colors?node-id=2012-78&t=Hme1IN8GkHrVfWHa-1 - new working file

**Comment by taysea** [comment]
Closing, the work here has been completed.
