### ISSUE TITLE
FileInput - Identify, annotate and commence an accessibility checklist

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#4124]
[FileInput Figma Accessibility File](https://www.figma.com/design/aoGbHTBIv0RH7UUuAt9a83/%234090---File-upload%2C-progress-bar?node-id=174-35669&t=9wnjYpFbZ82Jd3aW-1)
As we're looking to enhance our guidance on the accessibility relm, I've connected with Mike to understand what aria labels the FileInput implemented in Ethan uses to provide status on the progress bar when using a screen reader. I've asked if there are `aria-valuemin`, `aria-valuemax`, `aria-valuenow`, and `aria-busy` to help distinguish what’s happening?

Mike has checked the Grommet meter to see if set those automatically.  "Doesn't look like it. We'd have to decide to set them. I wonder if they are needed in this case given you already have the same info in text and don't need it reading things twice. Either way I'm sure this situation would need to be optimized to provide a decent experience"

FileInput Checklist:

- [ ] refer to Grommet
- [ ] utilize screen reader across other FileInputs
- [ ] identify areas of opportunity
- [ ] annotate
- [ ] create checklist
- [ ] add WCAG link
- [ ] work with devs along the way and share

I've started one in the link above.
